In [ ]:
import camelot
import pandas as pd

In [ ]:
exams_db = pd.read_excel("exams.xls", skip_rows=[0, 1, 2])

In [ ]:
exams_db

In [ ]:
exams_db

In [ ]:
exams_db

In [ ]:
exams_db = pd.read_excel("exams.xls", skiprows=[0, 1])

In [ ]:
exams_db

In [ ]:
exams_db = pd.read_excel("exams.xls", skiprows=[0, 1])

In [ ]:
exams_db

In [ ]:
exams_df_modified = exams_db.drop("Unnamed: 2", axis=1)

In [ ]:
exams_df_modified

In [ ]:
exams_df_modified1 = exams_db.drop("#", axis=1)

exams_df_modified1.drop('Unnamed: 2', axis=1, inplace=True)

In [ ]:
exams_df_modified1

In [ ]:
exams_df_modified1.drop(97, axis=0, inplace=True)

In [ ]:
exams_df_modified1

In [ ]:
exam_df_nearfinal = exams_df_modified1.rename("Öğrenci No", axis=1, "ID")

In [ ]:
exam_df_nearfinal = exams_df_modified1.rename(index=0, columns="Öğrenci No", axis=1, "ID")

In [ ]:
exam_df_nearfinal = exams_df_modified1.rename(index=0, columns="ID", axis=1)

In [ ]:
exam_df_nearfinal = exams_df_modified1.rename({"Öğrenci No": "ID"})

In [ ]:
exam_df_nearfinal

In [ ]:
exam_df_nearfinal = exams_df_modified1.rename({"ID": "Öğrenci No"}, axis=1)

In [ ]:
exam_df_nearfinal

In [ ]:
exam_df_nearfinal = exams_df_modified1.rename(columns={"Öğrenci No": "ID"})

In [ ]:
exam_df_nearfinal

In [ ]:
final = exam_df_nearfinal.set_option("display.colheader_justify","left")

In [ ]:
final = exam_df_nearfinal.style.set_properties({'text-align': 'right'})

In [ ]:
final

In [ ]:
final = exam_df_nearfinal.style.set_properties({'text-align': 'right'}, axis=1)

In [ ]:
final

In [ ]:
final = exam_df_nearfinal

In [ ]:
final

In [ ]:
final.to_pickle('without-labs.pkl')

In [ ]:
clear

In [ ]:
clear()

In [ ]:
test = camelot.read_pdf('lab.pdf', pages="1-end")

In [ ]:
test

In [ ]:
test[0].parsing_report

In [ ]:
test[0].df

In [1]:
import camelot
import pandas
import matplotlib

In [2]:
from matplotlib import pyplot as plt

In [3]:
import pandas as pd

In [5]:
df = pd.read_pickle("without-labs.pkl")

In [6]:
df

           ID  MIDTERM 1  MIDTERM 2  FINAL  LAB   ATTENDANCE  LETTER GRADE
0   210206004       24.0        0.0    NaN   NaN        0.45           NaN
1   210206040       62.0       25.0   65.0   NaN        0.60           NaN
2   220206017        NaN        NaN    NaN   NaN        0.00           NaN
3   220206047       46.0       45.0   28.0   NaN        0.65           NaN
4   230206003       29.0       40.0   24.0   NaN        0.70           NaN
5   230206007      100.0      100.0   63.0   NaN        1.00           NaN
6   230206012       83.0       95.0   85.0   NaN        0.80           NaN
7   230206023        NaN        NaN    NaN   NaN        0.00           NaN
8   230206031        NaN        NaN    NaN   NaN        0.00           NaN
9   230206046       81.0       70.0   60.0   NaN        1.00           NaN
10  230206057       48.0       60.0   32.0   NaN        0.90           NaN
11  240206004       55.0        4.0   31.0   NaN        0.45           NaN
12  240206011       82.0       95.0   56.0   NaN        0.60           NaN
13  240206023      100.0      105.0   81.0   NaN        1.00           NaN
14  240206025       84.0       70.0   71.0   NaN        0.60           NaN
15  240206026       58.0       13.0   41.0   NaN        0.75           NaN
16  240206028       37.0        0.0    NaN   NaN        0.45           NaN
17  240206031       49.0       50.0   57.0   NaN        0.70           NaN
18  240206043       56.0       30.0   40.0   NaN        0.95           NaN
19  240206047       63.0       30.0   53.0   NaN        0.90           NaN
20  240206048       66.0       15.0   36.0   NaN        0.65           NaN
21  240206052       26.0       35.0   24.0   NaN        0.80           NaN
22  240206053       74.0       45.0   40.0   NaN        0.65           NaN
23  240206103       54.0        5.0   31.0   NaN        0.75           NaN
24  240206131       17.0       40.0   19.0   NaN        0.85           NaN
25  240206157       14.0        NaN    NaN   NaN        0.00           NaN
26  240206176        8.0       17.0   12.0   NaN        0.60           NaN
27  250206001       95.0       65.0   64.0   NaN        0.85           NaN
28  250206002       56.0       20.0   67.0   NaN        0.85           NaN
29  250206004      100.0       95.0   54.0   NaN        1.00           NaN
..        ...        ...        ...    ...   ...         ...           ...
67  250206051        NaN        NaN    NaN   NaN        0.55           NaN
68  250206052       54.0      105.0   26.0   NaN        0.85           NaN
69  250206053       40.0       10.0   36.0   NaN        0.90           NaN
70  250206054       29.0       30.0   46.0   NaN        0.80           NaN
71  250206055        NaN        NaN    NaN   NaN        0.25           NaN
72  250206056       10.0        0.0    0.0   NaN        1.00           NaN
73  250206057       23.0       35.0   75.0   NaN        0.75           NaN
74  250206058       66.0       25.0   22.0   NaN        0.85           NaN
75  250206059       44.0       35.0   69.0   NaN        0.85           NaN
76  250206060       58.0       60.0   33.0   NaN        0.90           NaN
77  250206062       89.0       73.0   21.0   NaN        0.90           NaN
78  250206073       72.0       45.0   25.0   NaN        0.70           NaN
79  250206076        NaN        NaN    NaN   NaN        0.05           NaN
80  250206079        NaN        NaN    NaN   NaN        0.05           NaN
81  250206081       39.0       20.0    8.0   NaN        0.95           NaN
82  250206082       52.0        NaN    NaN   NaN        0.65           NaN
83  250206083       21.0        0.0   10.0   NaN        0.90           NaN
84  250206084        NaN        NaN    NaN   NaN        0.05           NaN
85  260206003       88.0       43.0   58.0   NaN        1.00           NaN
86  260206005        8.0       15.0   12.0   NaN        0.70           NaN
87  260206008       70.0       25.0   24.0   NaN        0.95           NaN
88  260206018       39.0        5.0    NaN   NaN        0.70           NaN
89  260206019       37.0        5.0   53.0   NaN        0.70           NaN
90  260206040       19.0       25.0   13.0   NaN        0.90           NaN
91  260206044       21.0        0.0    NaN   NaN        0.65           NaN
92  260206050       22.0       40.0   32.0   NaN        0.45           NaN
93  260206074       94.0       88.0   40.0   NaN        1.00           NaN
94  260206075       20.0        NaN    NaN   NaN        0.40           NaN
95  260206077       33.0       13.0    NaN   NaN        0.80           NaN
96  260206079        0.0        0.0    NaN   NaN        0.80           NaN

[97 rows x 7 columns]

In [7]:
tables = camelot.read_pdf('lab.pdf', pages="1-end")

In [8]:
tables

In [9]:
tables[0].parsing_report

{'accuracy': 99.27, 'whitespace': 1.98, 'order': 1, 'page': 1}

In [10]:
tables[1].parsing_report

{'accuracy': 99.19, 'whitespace': 1.79, 'order': 1, 'page': 2}

In [12]:
df_lab = pd.concat[tables[0].df, tables[1].df]

TypeError: 'function' object is not subscriptable

In [13]:
df_lab = pd.concat((tables[0].df), (tables[1].df)])

SyntaxError: invalid syntax (<ipython-input-13-650408d3549a>, line 1)

In [14]:
df_lab = pd.concat([tables[0].df, tables[1].df])

In [15]:
df_lab

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
1,1,210206004,MUHAMMET ÇİFTÇİ,100,90,,,30,100,20,...,100,,100 NA,,NA,NA,NA,NA,NA,45
2,2,210206040,FERHAT TEMÜR,70,100,100,100,100,100,90,...,100,65,100 NA,,NA,40,0,0,90,"62,94444444"
3,3,220206017,LÜTFİ DİNÇ,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
4,4,220206047,ERDOĞAN FİDAN,100,90,0,100,70,100,5,...,100,0,100 NA,,NA,NA,NA,NA,NA,"54,02777778"
5,5,230206003,AHMET DALGIÇ,100,90,100,100,100,100,30,...,100,0,100,50,100,40,70,0,100,"76,38888889"
6,6,230206007,ENGİN YUNUS GÜNER,100,100,100,100,40,100,80,...,100,75,100,50,100,100,80,50,100,"88,47222222"
7,7,230206012,EGEMEN ÖZKAYA,100,100,100,100,100,100,40,...,100,65,100,40,60,85,70,0,100,"78,33333333"
8,8,230206023,YİĞİT VATANSEVER,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
9,9,230206031,ONUR METE,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
10,10,230206046,EKİN ERİŞ,100,100,100,100,100,100,90,...,100,30,100,50,60,60,70,0,100,"75,69444444"
11,11,230206057,EFE KOCATAŞ,100,100,50,100,100,100,90,...,100,45,100,60,60,100,70,50,90,"81,66666667"
12,12,240206004,MİRZA FETHULLAH YARAN,100,100,100,100 NA,,NA,80,...,100,30,100,70,60,50,70,50,100,"70,02777778"
13,13,240206011,HAKAN AKAR,100,100,100,100,100,100,90,...,40,100,100,85,100,75,70,30,100,"82,77777778"
14,14,240206023,ZEHRA DENİZ SALMAN,100,100,50,100,100,100,70,...,100,60,100,80,100,100,70,20,85,"84,72222222"
15,15,240206025,ONUR TÜRKMEN,100,80,100,100,100,100,60,...,100,30,100,90,100,100,70,70,100,"88,88888889"
16,16,240206026,VOLKAN DEDE,70,100,50,100,10,100,35,...,100,15,100,40,100,30,50,50,90,"75,02777778"
17,17,240206028,MUHAMMED YUSUF ALTUN,100,100,50,100,70,100,0,...,100,0,100,0,,60 NA,NA,NA,NA,"62,5"
18,18,240206031,HÜSEYİN KAAN TÜRK,100,100,100,100,100,100,25,...,100,30,100,50,100,60,50,80,90,"84,44444444"
19,19,240206043,ONAT OKKAOĞLU,100,100,0,100,100,100,90,...,40,20,100,70,100,40,70,0,100,"70,97222222"
20,20,240206047,ONURALP SÖZDİNLEROĞLU,100,90,100,100,100,100,30,...,100,20,100,50,100,70,70,20,100,"78,75"
21,21,240206048,KUBİLAY KABATAŞ,40,100,,,70,100,15,...,100,65,100,70,100 NA,,NA,30,100,"71,25"
22,22,240206052,HÜSEYİN ATA YILMAZÇELİK,40,100,100,100,85,100,10,...,100,75,100,50,100,100,100,0,60,"82,22222222"
23,23,240206053,AHMED BURAK GÜLTEKİN,100,100,0,100,100,100,20,...,100,30,100,70,100,60,,70 NA,NA,"74,86111111"
24,24,240206103,HALİL İBRAHİM ALKAN,NA,100,0,80,55,30,30,...,NA,15,95,50,60,30,70,0,100,"49,58333333"
25,25,240206131,YİĞİTCAN DİRİK,40,100,50,100,25,100,20,...,100,5,100,20,100,10,100,0,60,"72,77777778"
26,26,240206157,ÖYKÜ ATCI,NA,NA,NA,NA,5,30,0,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,"2,638888889"
27,27,240206176,OKAN GÖKALP,45,100,50,100,30,100,1,...,100,0,100,20,,60 NA,NA,75,100,"67,41666667"
28,28,250206001,AHMET YASİN BULUT,100,100,100,100,70,100,90,...,100,45,100,90,100,90,70,30,100,"85,83333333"
29,29,250206002,ESİN DUYGU ÖZDEMİR,40,100,50,100,40,100,0,...,,50 NA,100,90,100,10,70,30,100,"69,75"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,69,250206052,GAMZE AYTEKİN,50,100,100,100,100,100,55,...,100,15,90,40,55,80,70,20,100,"74,16666667"
70,70,250206053,ÖZGÜR DEMİR,100,100,100,100,80,100,10,...,100,65,100,20,100,60,70,50,95,"81,94444444"
0,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
1,71,250206054,ALAATTİN ÇAKIRLAR,30,100,0,100,5,100,10,...,100 NA,,NA,0,100,35,70,0,70,"58,08333333"
2,72,250206055,AHMET YILMAZ,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
3,73,250206056,EGE AYDENİZ,100,100,100,70,0,100,0,...,30,0,100,0,90,1,,70 NA,NA,"60,61111111"
4,74,250206057,KADİR GÜRHAN KAYA,100,100,100,90,90,100,90,...,100,70,100,30,100,80,70,60,100,"87,22222222"
5,75,250206058,SEBAHATTİN YARICI,100,90,100,100,65,85,10,...,85,50,100,0,100,80,70,80,90,81
6,76,250206059,ÇAĞLA KARAHAN,100,100,50,100,100,100,45,...,100,100,100,90,100,80,70,20,85,"82,11111111"
7,77,250206060,MUHAMMED ALİ ŞAHİN,30,90,0,85,68,90,55,...,100,15,50,40,60,30,70,75,100,"70,36111111"
8,78,250206062,UTKU ACAR,100,100,100,100,100,100,50,...,100,40,100,70,100,85,70,50,100,"86,25"
9,79,250206073,BARIŞ BERKE ÇAĞLAR,100,90,100,100,50,100,25,...,100,100,90,0,95,100,70,50,100,"83,33333333"
10,80,250206076,ASİYE KURCAK,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
11,81,250206079,BERKAY ARPAT,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
12,82,250206081,CEM KARAGÖZ,100,100,100,90,70,100,80,...,100,0,70,30,60,70,40,20,100,70
13,83,250206082,ÖZCAN GEDİK,100,100,100,90,70,100,80,...,100 NA,,NA,NA,NA,NA,NA,NA,NA,"50,58333333"
14,84,250206083,EMRE GARİP,50,100,100,100,100,60,70,...,100,55,90,40,100,45,100,50,100,"80,97222222"
15,85,250206084,İZZET KALDAN,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
16,86,260206003,CEYHUN EFE KAYAN,50,100,100,100,95,100,70,...,100,30,100,60,100 NA,,NA,50,85,"75,41666667"
17,87,260206005,EGE GENİŞOĞLU,70,100,100,30,50,80,10,...,100,0,100,30,100,1,40,0,50,"61,55555556"
18,88,260206008,BARIŞ DENİZ GÖKMEN,100,100,100,100,88,60,85,...,100,50,90,40,100,45,100,80,100,"85,52777778"
19,89,260206018,ENES TÜFEKCİ,70,85,100,100,90,90,15,...,0,0,70,30,60,75,,40 NA,NA,56
20,90,260206019,ARDA SEVİNÇ,100,100,100,100,0,100,65,...,100,30,100,30,100,80,70,50,85,"81,52777778"
21,91,260206040,YAĞIZ TİRYAKİ,70,90,100,30,45,80,10,...,100,25,100,40,100,1,40,0,50,"61,55555556"
22,92,260206044,CAN KAYAN,20,75,0,100,20,90,10,...,,0 NA,100 NA,,,30 NA,NA,NA,NA,"42,63888889"
23,93,260206050,OKAN KARA,100,100,100,100,23,100,50,...,90,20,100,60,100,70,70,0,30,"70,94444444"
24,94,260206074,CELİL YILMAZ,100,90,100,85,100,90,60,...,100,30,50,20,60,95,70,40,100,75
25,95,260206075,MERT BURAK YASDIKCIOĞLU,70,100,100,100,25,100,45,...,,90 NA,NA,NA,NA,NA,NA,NA,NA,"47,63888889"
26,96,260206077,ZEYNEP GENİM,30,100,100,100,40,100,25,...,,90 NA,NA,40,70,10,70,0,100,"59,33333333"
27,97,260206079,MUTLU TAŞYER,30,100,100,100,90,90,10,...,100,10,100,0,100,30,,70 NA,NA,"70,86111111"

In [16]:
df_lab1 = df_lab.drop('#', axis=1)

KeyError: "['#'] not found in axis"

In [17]:
df_lab1 = df_lab

In [18]:
df_lab1.cols = df_lab.loc[0, axis=0]

SyntaxError: invalid syntax (<ipython-input-18-f4b84ece6d2f>, line 1)

In [19]:
df_lab1.cols = df_lab.loc[0]

/home/ardasevinc/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """Entry point for launching an IPython kernel.

In [20]:
df_lab1

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
1,1,210206004,MUHAMMET ÇİFTÇİ,100,90,,,30,100,20,...,100,,100 NA,,NA,NA,NA,NA,NA,45
2,2,210206040,FERHAT TEMÜR,70,100,100,100,100,100,90,...,100,65,100 NA,,NA,40,0,0,90,"62,94444444"
3,3,220206017,LÜTFİ DİNÇ,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
4,4,220206047,ERDOĞAN FİDAN,100,90,0,100,70,100,5,...,100,0,100 NA,,NA,NA,NA,NA,NA,"54,02777778"
5,5,230206003,AHMET DALGIÇ,100,90,100,100,100,100,30,...,100,0,100,50,100,40,70,0,100,"76,38888889"
6,6,230206007,ENGİN YUNUS GÜNER,100,100,100,100,40,100,80,...,100,75,100,50,100,100,80,50,100,"88,47222222"
7,7,230206012,EGEMEN ÖZKAYA,100,100,100,100,100,100,40,...,100,65,100,40,60,85,70,0,100,"78,33333333"
8,8,230206023,YİĞİT VATANSEVER,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
9,9,230206031,ONUR METE,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
10,10,230206046,EKİN ERİŞ,100,100,100,100,100,100,90,...,100,30,100,50,60,60,70,0,100,"75,69444444"
11,11,230206057,EFE KOCATAŞ,100,100,50,100,100,100,90,...,100,45,100,60,60,100,70,50,90,"81,66666667"
12,12,240206004,MİRZA FETHULLAH YARAN,100,100,100,100 NA,,NA,80,...,100,30,100,70,60,50,70,50,100,"70,02777778"
13,13,240206011,HAKAN AKAR,100,100,100,100,100,100,90,...,40,100,100,85,100,75,70,30,100,"82,77777778"
14,14,240206023,ZEHRA DENİZ SALMAN,100,100,50,100,100,100,70,...,100,60,100,80,100,100,70,20,85,"84,72222222"
15,15,240206025,ONUR TÜRKMEN,100,80,100,100,100,100,60,...,100,30,100,90,100,100,70,70,100,"88,88888889"
16,16,240206026,VOLKAN DEDE,70,100,50,100,10,100,35,...,100,15,100,40,100,30,50,50,90,"75,02777778"
17,17,240206028,MUHAMMED YUSUF ALTUN,100,100,50,100,70,100,0,...,100,0,100,0,,60 NA,NA,NA,NA,"62,5"
18,18,240206031,HÜSEYİN KAAN TÜRK,100,100,100,100,100,100,25,...,100,30,100,50,100,60,50,80,90,"84,44444444"
19,19,240206043,ONAT OKKAOĞLU,100,100,0,100,100,100,90,...,40,20,100,70,100,40,70,0,100,"70,97222222"
20,20,240206047,ONURALP SÖZDİNLEROĞLU,100,90,100,100,100,100,30,...,100,20,100,50,100,70,70,20,100,"78,75"
21,21,240206048,KUBİLAY KABATAŞ,40,100,,,70,100,15,...,100,65,100,70,100 NA,,NA,30,100,"71,25"
22,22,240206052,HÜSEYİN ATA YILMAZÇELİK,40,100,100,100,85,100,10,...,100,75,100,50,100,100,100,0,60,"82,22222222"
23,23,240206053,AHMED BURAK GÜLTEKİN,100,100,0,100,100,100,20,...,100,30,100,70,100,60,,70 NA,NA,"74,86111111"
24,24,240206103,HALİL İBRAHİM ALKAN,NA,100,0,80,55,30,30,...,NA,15,95,50,60,30,70,0,100,"49,58333333"
25,25,240206131,YİĞİTCAN DİRİK,40,100,50,100,25,100,20,...,100,5,100,20,100,10,100,0,60,"72,77777778"
26,26,240206157,ÖYKÜ ATCI,NA,NA,NA,NA,5,30,0,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,"2,638888889"
27,27,240206176,OKAN GÖKALP,45,100,50,100,30,100,1,...,100,0,100,20,,60 NA,NA,75,100,"67,41666667"
28,28,250206001,AHMET YASİN BULUT,100,100,100,100,70,100,90,...,100,45,100,90,100,90,70,30,100,"85,83333333"
29,29,250206002,ESİN DUYGU ÖZDEMİR,40,100,50,100,40,100,0,...,,50 NA,100,90,100,10,70,30,100,"69,75"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,69,250206052,GAMZE AYTEKİN,50,100,100,100,100,100,55,...,100,15,90,40,55,80,70,20,100,"74,16666667"
70,70,250206053,ÖZGÜR DEMİR,100,100,100,100,80,100,10,...,100,65,100,20,100,60,70,50,95,"81,94444444"
0,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
1,71,250206054,ALAATTİN ÇAKIRLAR,30,100,0,100,5,100,10,...,100 NA,,NA,0,100,35,70,0,70,"58,08333333"
2,72,250206055,AHMET YILMAZ,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
3,73,250206056,EGE AYDENİZ,100,100,100,70,0,100,0,...,30,0,100,0,90,1,,70 NA,NA,"60,61111111"
4,74,250206057,KADİR GÜRHAN KAYA,100,100,100,90,90,100,90,...,100,70,100,30,100,80,70,60,100,"87,22222222"
5,75,250206058,SEBAHATTİN YARICI,100,90,100,100,65,85,10,...,85,50,100,0,100,80,70,80,90,81
6,76,250206059,ÇAĞLA KARAHAN,100,100,50,100,100,100,45,...,100,100,100,90,100,80,70,20,85,"82,11111111"
7,77,250206060,MUHAMMED ALİ ŞAHİN,30,90,0,85,68,90,55,...,100,15,50,40,60,30,70,75,100,"70,36111111"
8,78,250206062,UTKU ACAR,100,100,100,100,100,100,50,...,100,40,100,70,100,85,70,50,100,"86,25"
9,79,250206073,BARIŞ BERKE ÇAĞLAR,100,90,100,100,50,100,25,...,100,100,90,0,95,100,70,50,100,"83,33333333"
10,80,250206076,ASİYE KURCAK,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
11,81,250206079,BERKAY ARPAT,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
12,82,250206081,CEM KARAGÖZ,100,100,100,90,70,100,80,...,100,0,70,30,60,70,40,20,100,70
13,83,250206082,ÖZCAN GEDİK,100,100,100,90,70,100,80,...,100 NA,,NA,NA,NA,NA,NA,NA,NA,"50,58333333"
14,84,250206083,EMRE GARİP,50,100,100,100,100,60,70,...,100,55,90,40,100,45,100,50,100,"80,97222222"
15,85,250206084,İZZET KALDAN,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
16,86,260206003,CEYHUN EFE KAYAN,50,100,100,100,95,100,70,...,100,30,100,60,100 NA,,NA,50,85,"75,41666667"
17,87,260206005,EGE GENİŞOĞLU,70,100,100,30,50,80,10,...,100,0,100,30,100,1,40,0,50,"61,55555556"
18,88,260206008,BARIŞ DENİZ GÖKMEN,100,100,100,100,88,60,85,...,100,50,90,40,100,45,100,80,100,"85,52777778"
19,89,260206018,ENES TÜFEKCİ,70,85,100,100,90,90,15,...,0,0,70,30,60,75,,40 NA,NA,56
20,90,260206019,ARDA SEVİNÇ,100,100,100,100,0,100,65,...,100,30,100,30,100,80,70,50,85,"81,52777778"
21,91,260206040,YAĞIZ TİRYAKİ,70,90,100,30,45,80,10,...,100,25,100,40,100,1,40,0,50,"61,55555556"
22,92,260206044,CAN KAYAN,20,75,0,100,20,90,10,...,,0 NA,100 NA,,,30 NA,NA,NA,NA,"42,63888889"
23,93,260206050,OKAN KARA,100,100,100,100,23,100,50,...,90,20,100,60,100,70,70,0,30,"70,94444444"
24,94,260206074,CELİL YILMAZ,100,90,100,85,100,90,60,...,100,30,50,20,60,95,70,40,100,75
25,95,260206075,MERT BURAK YASDIKCIOĞLU,70,100,100,100,25,100,45,...,,90 NA,NA,NA,NA,NA,NA,NA,NA,"47,63888889"
26,96,260206077,ZEYNEP GENİM,30,100,100,100,40,100,25,...,,90 NA,NA,40,70,10,70,0,100,"59,33333333"
27,97,260206079,MUTLU TAŞYER,30,100,100,100,90,90,10,...,100,10,100,0,100,30,,70 NA,NA,"70,86111111"

In [21]:
df_lab.loc[0]

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
0,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade

In [22]:
df_lab

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
1,1,210206004,MUHAMMET ÇİFTÇİ,100,90,,,30,100,20,...,100,,100 NA,,NA,NA,NA,NA,NA,45
2,2,210206040,FERHAT TEMÜR,70,100,100,100,100,100,90,...,100,65,100 NA,,NA,40,0,0,90,"62,94444444"
3,3,220206017,LÜTFİ DİNÇ,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
4,4,220206047,ERDOĞAN FİDAN,100,90,0,100,70,100,5,...,100,0,100 NA,,NA,NA,NA,NA,NA,"54,02777778"
5,5,230206003,AHMET DALGIÇ,100,90,100,100,100,100,30,...,100,0,100,50,100,40,70,0,100,"76,38888889"
6,6,230206007,ENGİN YUNUS GÜNER,100,100,100,100,40,100,80,...,100,75,100,50,100,100,80,50,100,"88,47222222"
7,7,230206012,EGEMEN ÖZKAYA,100,100,100,100,100,100,40,...,100,65,100,40,60,85,70,0,100,"78,33333333"
8,8,230206023,YİĞİT VATANSEVER,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
9,9,230206031,ONUR METE,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
10,10,230206046,EKİN ERİŞ,100,100,100,100,100,100,90,...,100,30,100,50,60,60,70,0,100,"75,69444444"
11,11,230206057,EFE KOCATAŞ,100,100,50,100,100,100,90,...,100,45,100,60,60,100,70,50,90,"81,66666667"
12,12,240206004,MİRZA FETHULLAH YARAN,100,100,100,100 NA,,NA,80,...,100,30,100,70,60,50,70,50,100,"70,02777778"
13,13,240206011,HAKAN AKAR,100,100,100,100,100,100,90,...,40,100,100,85,100,75,70,30,100,"82,77777778"
14,14,240206023,ZEHRA DENİZ SALMAN,100,100,50,100,100,100,70,...,100,60,100,80,100,100,70,20,85,"84,72222222"
15,15,240206025,ONUR TÜRKMEN,100,80,100,100,100,100,60,...,100,30,100,90,100,100,70,70,100,"88,88888889"
16,16,240206026,VOLKAN DEDE,70,100,50,100,10,100,35,...,100,15,100,40,100,30,50,50,90,"75,02777778"
17,17,240206028,MUHAMMED YUSUF ALTUN,100,100,50,100,70,100,0,...,100,0,100,0,,60 NA,NA,NA,NA,"62,5"
18,18,240206031,HÜSEYİN KAAN TÜRK,100,100,100,100,100,100,25,...,100,30,100,50,100,60,50,80,90,"84,44444444"
19,19,240206043,ONAT OKKAOĞLU,100,100,0,100,100,100,90,...,40,20,100,70,100,40,70,0,100,"70,97222222"
20,20,240206047,ONURALP SÖZDİNLEROĞLU,100,90,100,100,100,100,30,...,100,20,100,50,100,70,70,20,100,"78,75"
21,21,240206048,KUBİLAY KABATAŞ,40,100,,,70,100,15,...,100,65,100,70,100 NA,,NA,30,100,"71,25"
22,22,240206052,HÜSEYİN ATA YILMAZÇELİK,40,100,100,100,85,100,10,...,100,75,100,50,100,100,100,0,60,"82,22222222"
23,23,240206053,AHMED BURAK GÜLTEKİN,100,100,0,100,100,100,20,...,100,30,100,70,100,60,,70 NA,NA,"74,86111111"
24,24,240206103,HALİL İBRAHİM ALKAN,NA,100,0,80,55,30,30,...,NA,15,95,50,60,30,70,0,100,"49,58333333"
25,25,240206131,YİĞİTCAN DİRİK,40,100,50,100,25,100,20,...,100,5,100,20,100,10,100,0,60,"72,77777778"
26,26,240206157,ÖYKÜ ATCI,NA,NA,NA,NA,5,30,0,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,"2,638888889"
27,27,240206176,OKAN GÖKALP,45,100,50,100,30,100,1,...,100,0,100,20,,60 NA,NA,75,100,"67,41666667"
28,28,250206001,AHMET YASİN BULUT,100,100,100,100,70,100,90,...,100,45,100,90,100,90,70,30,100,"85,83333333"
29,29,250206002,ESİN DUYGU ÖZDEMİR,40,100,50,100,40,100,0,...,,50 NA,100,90,100,10,70,30,100,"69,75"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,69,250206052,GAMZE AYTEKİN,50,100,100,100,100,100,55,...,100,15,90,40,55,80,70,20,100,"74,16666667"
70,70,250206053,ÖZGÜR DEMİR,100,100,100,100,80,100,10,...,100,65,100,20,100,60,70,50,95,"81,94444444"
0,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
1,71,250206054,ALAATTİN ÇAKIRLAR,30,100,0,100,5,100,10,...,100 NA,,NA,0,100,35,70,0,70,"58,08333333"
2,72,250206055,AHMET YILMAZ,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
3,73,250206056,EGE AYDENİZ,100,100,100,70,0,100,0,...,30,0,100,0,90,1,,70 NA,NA,"60,61111111"
4,74,250206057,KADİR GÜRHAN KAYA,100,100,100,90,90,100,90,...,100,70,100,30,100,80,70,60,100,"87,22222222"
5,75,250206058,SEBAHATTİN YARICI,100,90,100,100,65,85,10,...,85,50,100,0,100,80,70,80,90,81
6,76,250206059,ÇAĞLA KARAHAN,100,100,50,100,100,100,45,...,100,100,100,90,100,80,70,20,85,"82,11111111"
7,77,250206060,MUHAMMED ALİ ŞAHİN,30,90,0,85,68,90,55,...,100,15,50,40,60,30,70,75,100,"70,36111111"
8,78,250206062,UTKU ACAR,100,100,100,100,100,100,50,...,100,40,100,70,100,85,70,50,100,"86,25"
9,79,250206073,BARIŞ BERKE ÇAĞLAR,100,90,100,100,50,100,25,...,100,100,90,0,95,100,70,50,100,"83,33333333"
10,80,250206076,ASİYE KURCAK,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
11,81,250206079,BERKAY ARPAT,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
12,82,250206081,CEM KARAGÖZ,100,100,100,90,70,100,80,...,100,0,70,30,60,70,40,20,100,70
13,83,250206082,ÖZCAN GEDİK,100,100,100,90,70,100,80,...,100 NA,,NA,NA,NA,NA,NA,NA,NA,"50,58333333"
14,84,250206083,EMRE GARİP,50,100,100,100,100,60,70,...,100,55,90,40,100,45,100,50,100,"80,97222222"
15,85,250206084,İZZET KALDAN,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
16,86,260206003,CEYHUN EFE KAYAN,50,100,100,100,95,100,70,...,100,30,100,60,100 NA,,NA,50,85,"75,41666667"
17,87,260206005,EGE GENİŞOĞLU,70,100,100,30,50,80,10,...,100,0,100,30,100,1,40,0,50,"61,55555556"
18,88,260206008,BARIŞ DENİZ GÖKMEN,100,100,100,100,88,60,85,...,100,50,90,40,100,45,100,80,100,"85,52777778"
19,89,260206018,ENES TÜFEKCİ,70,85,100,100,90,90,15,...,0,0,70,30,60,75,,40 NA,NA,56
20,90,260206019,ARDA SEVİNÇ,100,100,100,100,0,100,65,...,100,30,100,30,100,80,70,50,85,"81,52777778"
21,91,260206040,YAĞIZ TİRYAKİ,70,90,100,30,45,80,10,...,100,25,100,40,100,1,40,0,50,"61,55555556"
22,92,260206044,CAN KAYAN,20,75,0,100,20,90,10,...,,0 NA,100 NA,,,30 NA,NA,NA,NA,"42,63888889"
23,93,260206050,OKAN KARA,100,100,100,100,23,100,50,...,90,20,100,60,100,70,70,0,30,"70,94444444"
24,94,260206074,CELİL YILMAZ,100,90,100,85,100,90,60,...,100,30,50,20,60,95,70,40,100,75
25,95,260206075,MERT BURAK YASDIKCIOĞLU,70,100,100,100,25,100,45,...,,90 NA,NA,NA,NA,NA,NA,NA,NA,"47,63888889"
26,96,260206077,ZEYNEP GENİM,30,100,100,100,40,100,25,...,,90 NA,NA,40,70,10,70,0,100,"59,33333333"
27,97,260206079,MUTLU TAŞYER,30,100,100,100,90,90,10,...,100,10,100,0,100,30,,70 NA,NA,"70,86111111"

In [23]:
df_lab.loc[0]

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
0,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade

In [24]:
df_lab.loc[1]

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
1,1,210206004,MUHAMMET ÇİFTÇİ,100,90,,,30,100,20,...,100,,100 NA,,NA,NA,NA,NA,NA,45
1,71,250206054,ALAATTİN ÇAKIRLAR,30,100,0,100,5,100,10,...,100 NA,,NA,0,100,35,70,0,70,"58,08333333"

In [25]:
df_lab.loc["0"]

KeyError: '0'

In [26]:
df_lab1 = df_lab.reset_index()

In [27]:
df_lab1

,index,0,1,2,3,4,5,6,7,8,...,12,13,14,15,16,17,18,19,20,21
0,0,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
1,1,1,210206004,MUHAMMET ÇİFTÇİ,100,90,,,30,100,...,100,,100 NA,,NA,NA,NA,NA,NA,45
2,2,2,210206040,FERHAT TEMÜR,70,100,100,100,100,100,...,100,65,100 NA,,NA,40,0,0,90,"62,94444444"
3,3,3,220206017,LÜTFİ DİNÇ,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
4,4,4,220206047,ERDOĞAN FİDAN,100,90,0,100,70,100,...,100,0,100 NA,,NA,NA,NA,NA,NA,"54,02777778"
5,5,5,230206003,AHMET DALGIÇ,100,90,100,100,100,100,...,100,0,100,50,100,40,70,0,100,"76,38888889"
6,6,6,230206007,ENGİN YUNUS GÜNER,100,100,100,100,40,100,...,100,75,100,50,100,100,80,50,100,"88,47222222"
7,7,7,230206012,EGEMEN ÖZKAYA,100,100,100,100,100,100,...,100,65,100,40,60,85,70,0,100,"78,33333333"
8,8,8,230206023,YİĞİT VATANSEVER,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
9,9,9,230206031,ONUR METE,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
10,10,10,230206046,EKİN ERİŞ,100,100,100,100,100,100,...,100,30,100,50,60,60,70,0,100,"75,69444444"
11,11,11,230206057,EFE KOCATAŞ,100,100,50,100,100,100,...,100,45,100,60,60,100,70,50,90,"81,66666667"
12,12,12,240206004,MİRZA FETHULLAH YARAN,100,100,100,100 NA,,NA,...,100,30,100,70,60,50,70,50,100,"70,02777778"
13,13,13,240206011,HAKAN AKAR,100,100,100,100,100,100,...,40,100,100,85,100,75,70,30,100,"82,77777778"
14,14,14,240206023,ZEHRA DENİZ SALMAN,100,100,50,100,100,100,...,100,60,100,80,100,100,70,20,85,"84,72222222"
15,15,15,240206025,ONUR TÜRKMEN,100,80,100,100,100,100,...,100,30,100,90,100,100,70,70,100,"88,88888889"
16,16,16,240206026,VOLKAN DEDE,70,100,50,100,10,100,...,100,15,100,40,100,30,50,50,90,"75,02777778"
17,17,17,240206028,MUHAMMED YUSUF ALTUN,100,100,50,100,70,100,...,100,0,100,0,,60 NA,NA,NA,NA,"62,5"
18,18,18,240206031,HÜSEYİN KAAN TÜRK,100,100,100,100,100,100,...,100,30,100,50,100,60,50,80,90,"84,44444444"
19,19,19,240206043,ONAT OKKAOĞLU,100,100,0,100,100,100,...,40,20,100,70,100,40,70,0,100,"70,97222222"
20,20,20,240206047,ONURALP SÖZDİNLEROĞLU,100,90,100,100,100,100,...,100,20,100,50,100,70,70,20,100,"78,75"
21,21,21,240206048,KUBİLAY KABATAŞ,40,100,,,70,100,...,100,65,100,70,100 NA,,NA,30,100,"71,25"
22,22,22,240206052,HÜSEYİN ATA YILMAZÇELİK,40,100,100,100,85,100,...,100,75,100,50,100,100,100,0,60,"82,22222222"
23,23,23,240206053,AHMED BURAK GÜLTEKİN,100,100,0,100,100,100,...,100,30,100,70,100,60,,70 NA,NA,"74,86111111"
24,24,24,240206103,HALİL İBRAHİM ALKAN,NA,100,0,80,55,30,...,NA,15,95,50,60,30,70,0,100,"49,58333333"
25,25,25,240206131,YİĞİTCAN DİRİK,40,100,50,100,25,100,...,100,5,100,20,100,10,100,0,60,"72,77777778"
26,26,26,240206157,ÖYKÜ ATCI,NA,NA,NA,NA,5,30,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,"2,638888889"
27,27,27,240206176,OKAN GÖKALP,45,100,50,100,30,100,...,100,0,100,20,,60 NA,NA,75,100,"67,41666667"
28,28,28,250206001,AHMET YASİN BULUT,100,100,100,100,70,100,...,100,45,100,90,100,90,70,30,100,"85,83333333"
29,29,29,250206002,ESİN DUYGU ÖZDEMİR,40,100,50,100,40,100,...,,50 NA,100,90,100,10,70,30,100,"69,75"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,69,69,250206052,GAMZE AYTEKİN,50,100,100,100,100,100,...,100,15,90,40,55,80,70,20,100,"74,16666667"
70,70,70,250206053,ÖZGÜR DEMİR,100,100,100,100,80,100,...,100,65,100,20,100,60,70,50,95,"81,94444444"
71,0,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
72,1,71,250206054,ALAATTİN ÇAKIRLAR,30,100,0,100,5,100,...,100 NA,,NA,0,100,35,70,0,70,"58,08333333"
73,2,72,250206055,AHMET YILMAZ,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
74,3,73,250206056,EGE AYDENİZ,100,100,100,70,0,100,...,30,0,100,0,90,1,,70 NA,NA,"60,61111111"
75,4,74,250206057,KADİR GÜRHAN KAYA,100,100,100,90,90,100,...,100,70,100,30,100,80,70,60,100,"87,22222222"
76,5,75,250206058,SEBAHATTİN YARICI,100,90,100,100,65,85,...,85,50,100,0,100,80,70,80,90,81
77,6,76,250206059,ÇAĞLA KARAHAN,100,100,50,100,100,100,...,100,100,100,90,100,80,70,20,85,"82,11111111"
78,7,77,250206060,MUHAMMED ALİ ŞAHİN,30,90,0,85,68,90,...,100,15,50,40,60,30,70,75,100,"70,36111111"
79,8,78,250206062,UTKU ACAR,100,100,100,100,100,100,...,100,40,100,70,100,85,70,50,100,"86,25"
80,9,79,250206073,BARIŞ BERKE ÇAĞLAR,100,90,100,100,50,100,...,100,100,90,0,95,100,70,50,100,"83,33333333"
81,10,80,250206076,ASİYE KURCAK,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
82,11,81,250206079,BERKAY ARPAT,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
83,12,82,250206081,CEM KARAGÖZ,100,100,100,90,70,100,...,100,0,70,30,60,70,40,20,100,70
84,13,83,250206082,ÖZCAN GEDİK,100,100,100,90,70,100,...,100 NA,,NA,NA,NA,NA,NA,NA,NA,"50,58333333"
85,14,84,250206083,EMRE GARİP,50,100,100,100,100,60,...,100,55,90,40,100,45,100,50,100,"80,97222222"
86,15,85,250206084,İZZET KALDAN,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
87,16,86,260206003,CEYHUN EFE KAYAN,50,100,100,100,95,100,...,100,30,100,60,100 NA,,NA,50,85,"75,41666667"
88,17,87,260206005,EGE GENİŞOĞLU,70,100,100,30,50,80,...,100,0,100,30,100,1,40,0,50,"61,55555556"
89,18,88,260206008,BARIŞ DENİZ GÖKMEN,100,100,100,100,88,60,...,100,50,90,40,100,45,100,80,100,"85,52777778"
90,19,89,260206018,ENES TÜFEKCİ,70,85,100,100,90,90,...,0,0,70,30,60,75,,40 NA,NA,56
91,20,90,260206019,ARDA SEVİNÇ,100,100,100,100,0,100,...,100,30,100,30,100,80,70,50,85,"81,52777778"
92,21,91,260206040,YAĞIZ TİRYAKİ,70,90,100,30,45,80,...,100,25,100,40,100,1,40,0,50,"61,55555556"
93,22,92,260206044,CAN KAYAN,20,75,0,100,20,90,...,,0 NA,100 NA,,,30 NA,NA,NA,NA,"42,63888889"
94,23,93,260206050,OKAN KARA,100,100,100,100,23,100,...,90,20,100,60,100,70,70,0,30,"70,94444444"
95,24,94,260206074,CELİL YILMAZ,100,90,100,85,100,90,...,100,30,50,20,60,95,70,40,100,75
96,25,95,260206075,MERT BURAK YASDIKCIOĞLU,70,100,100,100,25,100,...,,90 NA,NA,NA,NA,NA,NA,NA,NA,"47,63888889"
97,26,96,260206077,ZEYNEP GENİM,30,100,100,100,40,100,...,,90 NA,NA,40,70,10,70,0,100,"59,33333333"
98,27,97,260206079,MUTLU TAŞYER,30,100,100,100,90,90,...,100,10,100,0,100,30,,70 NA,NA,"70,86111111"

In [28]:
df_lab1 = df_lab.reset_index(drop=True)

In [29]:
df_lab1

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
1,1,210206004,MUHAMMET ÇİFTÇİ,100,90,,,30,100,20,...,100,,100 NA,,NA,NA,NA,NA,NA,45
2,2,210206040,FERHAT TEMÜR,70,100,100,100,100,100,90,...,100,65,100 NA,,NA,40,0,0,90,"62,94444444"
3,3,220206017,LÜTFİ DİNÇ,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
4,4,220206047,ERDOĞAN FİDAN,100,90,0,100,70,100,5,...,100,0,100 NA,,NA,NA,NA,NA,NA,"54,02777778"
5,5,230206003,AHMET DALGIÇ,100,90,100,100,100,100,30,...,100,0,100,50,100,40,70,0,100,"76,38888889"
6,6,230206007,ENGİN YUNUS GÜNER,100,100,100,100,40,100,80,...,100,75,100,50,100,100,80,50,100,"88,47222222"
7,7,230206012,EGEMEN ÖZKAYA,100,100,100,100,100,100,40,...,100,65,100,40,60,85,70,0,100,"78,33333333"
8,8,230206023,YİĞİT VATANSEVER,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
9,9,230206031,ONUR METE,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
10,10,230206046,EKİN ERİŞ,100,100,100,100,100,100,90,...,100,30,100,50,60,60,70,0,100,"75,69444444"
11,11,230206057,EFE KOCATAŞ,100,100,50,100,100,100,90,...,100,45,100,60,60,100,70,50,90,"81,66666667"
12,12,240206004,MİRZA FETHULLAH YARAN,100,100,100,100 NA,,NA,80,...,100,30,100,70,60,50,70,50,100,"70,02777778"
13,13,240206011,HAKAN AKAR,100,100,100,100,100,100,90,...,40,100,100,85,100,75,70,30,100,"82,77777778"
14,14,240206023,ZEHRA DENİZ SALMAN,100,100,50,100,100,100,70,...,100,60,100,80,100,100,70,20,85,"84,72222222"
15,15,240206025,ONUR TÜRKMEN,100,80,100,100,100,100,60,...,100,30,100,90,100,100,70,70,100,"88,88888889"
16,16,240206026,VOLKAN DEDE,70,100,50,100,10,100,35,...,100,15,100,40,100,30,50,50,90,"75,02777778"
17,17,240206028,MUHAMMED YUSUF ALTUN,100,100,50,100,70,100,0,...,100,0,100,0,,60 NA,NA,NA,NA,"62,5"
18,18,240206031,HÜSEYİN KAAN TÜRK,100,100,100,100,100,100,25,...,100,30,100,50,100,60,50,80,90,"84,44444444"
19,19,240206043,ONAT OKKAOĞLU,100,100,0,100,100,100,90,...,40,20,100,70,100,40,70,0,100,"70,97222222"
20,20,240206047,ONURALP SÖZDİNLEROĞLU,100,90,100,100,100,100,30,...,100,20,100,50,100,70,70,20,100,"78,75"
21,21,240206048,KUBİLAY KABATAŞ,40,100,,,70,100,15,...,100,65,100,70,100 NA,,NA,30,100,"71,25"
22,22,240206052,HÜSEYİN ATA YILMAZÇELİK,40,100,100,100,85,100,10,...,100,75,100,50,100,100,100,0,60,"82,22222222"
23,23,240206053,AHMED BURAK GÜLTEKİN,100,100,0,100,100,100,20,...,100,30,100,70,100,60,,70 NA,NA,"74,86111111"
24,24,240206103,HALİL İBRAHİM ALKAN,NA,100,0,80,55,30,30,...,NA,15,95,50,60,30,70,0,100,"49,58333333"
25,25,240206131,YİĞİTCAN DİRİK,40,100,50,100,25,100,20,...,100,5,100,20,100,10,100,0,60,"72,77777778"
26,26,240206157,ÖYKÜ ATCI,NA,NA,NA,NA,5,30,0,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,"2,638888889"
27,27,240206176,OKAN GÖKALP,45,100,50,100,30,100,1,...,100,0,100,20,,60 NA,NA,75,100,"67,41666667"
28,28,250206001,AHMET YASİN BULUT,100,100,100,100,70,100,90,...,100,45,100,90,100,90,70,30,100,"85,83333333"
29,29,250206002,ESİN DUYGU ÖZDEMİR,40,100,50,100,40,100,0,...,,50 NA,100,90,100,10,70,30,100,"69,75"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,69,250206052,GAMZE AYTEKİN,50,100,100,100,100,100,55,...,100,15,90,40,55,80,70,20,100,"74,16666667"
70,70,250206053,ÖZGÜR DEMİR,100,100,100,100,80,100,10,...,100,65,100,20,100,60,70,50,95,"81,94444444"
71,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
72,71,250206054,ALAATTİN ÇAKIRLAR,30,100,0,100,5,100,10,...,100 NA,,NA,0,100,35,70,0,70,"58,08333333"
73,72,250206055,AHMET YILMAZ,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
74,73,250206056,EGE AYDENİZ,100,100,100,70,0,100,0,...,30,0,100,0,90,1,,70 NA,NA,"60,61111111"
75,74,250206057,KADİR GÜRHAN KAYA,100,100,100,90,90,100,90,...,100,70,100,30,100,80,70,60,100,"87,22222222"
76,75,250206058,SEBAHATTİN YARICI,100,90,100,100,65,85,10,...,85,50,100,0,100,80,70,80,90,81
77,76,250206059,ÇAĞLA KARAHAN,100,100,50,100,100,100,45,...,100,100,100,90,100,80,70,20,85,"82,11111111"
78,77,250206060,MUHAMMED ALİ ŞAHİN,30,90,0,85,68,90,55,...,100,15,50,40,60,30,70,75,100,"70,36111111"
79,78,250206062,UTKU ACAR,100,100,100,100,100,100,50,...,100,40,100,70,100,85,70,50,100,"86,25"
80,79,250206073,BARIŞ BERKE ÇAĞLAR,100,90,100,100,50,100,25,...,100,100,90,0,95,100,70,50,100,"83,33333333"
81,80,250206076,ASİYE KURCAK,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
82,81,250206079,BERKAY ARPAT,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
83,82,250206081,CEM KARAGÖZ,100,100,100,90,70,100,80,...,100,0,70,30,60,70,40,20,100,70
84,83,250206082,ÖZCAN GEDİK,100,100,100,90,70,100,80,...,100 NA,,NA,NA,NA,NA,NA,NA,NA,"50,58333333"
85,84,250206083,EMRE GARİP,50,100,100,100,100,60,70,...,100,55,90,40,100,45,100,50,100,"80,97222222"
86,85,250206084,İZZET KALDAN,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
87,86,260206003,CEYHUN EFE KAYAN,50,100,100,100,95,100,70,...,100,30,100,60,100 NA,,NA,50,85,"75,41666667"
88,87,260206005,EGE GENİŞOĞLU,70,100,100,30,50,80,10,...,100,0,100,30,100,1,40,0,50,"61,55555556"
89,88,260206008,BARIŞ DENİZ GÖKMEN,100,100,100,100,88,60,85,...,100,50,90,40,100,45,100,80,100,"85,52777778"
90,89,260206018,ENES TÜFEKCİ,70,85,100,100,90,90,15,...,0,0,70,30,60,75,,40 NA,NA,56
91,90,260206019,ARDA SEVİNÇ,100,100,100,100,0,100,65,...,100,30,100,30,100,80,70,50,85,"81,52777778"
92,91,260206040,YAĞIZ TİRYAKİ,70,90,100,30,45,80,10,...,100,25,100,40,100,1,40,0,50,"61,55555556"
93,92,260206044,CAN KAYAN,20,75,0,100,20,90,10,...,,0 NA,100 NA,,,30 NA,NA,NA,NA,"42,63888889"
94,93,260206050,OKAN KARA,100,100,100,100,23,100,50,...,90,20,100,60,100,70,70,0,30,"70,94444444"
95,94,260206074,CELİL YILMAZ,100,90,100,85,100,90,60,...,100,30,50,20,60,95,70,40,100,75
96,95,260206075,MERT BURAK YASDIKCIOĞLU,70,100,100,100,25,100,45,...,,90 NA,NA,NA,NA,NA,NA,NA,NA,"47,63888889"
97,96,260206077,ZEYNEP GENİM,30,100,100,100,40,100,25,...,,90 NA,NA,40,70,10,70,0,100,"59,33333333"
98,97,260206079,MUTLU TAŞYER,30,100,100,100,90,90,10,...,100,10,100,0,100,30,,70 NA,NA,"70,86111111"

In [30]:
df_lab1.columns = df_lab1.loc[0]

In [31]:
df_lab1

,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
0,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
1,1,210206004,MUHAMMET ÇİFTÇİ,100,90,,,30,100,20,...,100,,100 NA,,NA,NA,NA,NA,NA,45
2,2,210206040,FERHAT TEMÜR,70,100,100,100,100,100,90,...,100,65,100 NA,,NA,40,0,0,90,"62,94444444"
3,3,220206017,LÜTFİ DİNÇ,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
4,4,220206047,ERDOĞAN FİDAN,100,90,0,100,70,100,5,...,100,0,100 NA,,NA,NA,NA,NA,NA,"54,02777778"
5,5,230206003,AHMET DALGIÇ,100,90,100,100,100,100,30,...,100,0,100,50,100,40,70,0,100,"76,38888889"
6,6,230206007,ENGİN YUNUS GÜNER,100,100,100,100,40,100,80,...,100,75,100,50,100,100,80,50,100,"88,47222222"
7,7,230206012,EGEMEN ÖZKAYA,100,100,100,100,100,100,40,...,100,65,100,40,60,85,70,0,100,"78,33333333"
8,8,230206023,YİĞİT VATANSEVER,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
9,9,230206031,ONUR METE,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
10,10,230206046,EKİN ERİŞ,100,100,100,100,100,100,90,...,100,30,100,50,60,60,70,0,100,"75,69444444"
11,11,230206057,EFE KOCATAŞ,100,100,50,100,100,100,90,...,100,45,100,60,60,100,70,50,90,"81,66666667"
12,12,240206004,MİRZA FETHULLAH YARAN,100,100,100,100 NA,,NA,80,...,100,30,100,70,60,50,70,50,100,"70,02777778"
13,13,240206011,HAKAN AKAR,100,100,100,100,100,100,90,...,40,100,100,85,100,75,70,30,100,"82,77777778"
14,14,240206023,ZEHRA DENİZ SALMAN,100,100,50,100,100,100,70,...,100,60,100,80,100,100,70,20,85,"84,72222222"
15,15,240206025,ONUR TÜRKMEN,100,80,100,100,100,100,60,...,100,30,100,90,100,100,70,70,100,"88,88888889"
16,16,240206026,VOLKAN DEDE,70,100,50,100,10,100,35,...,100,15,100,40,100,30,50,50,90,"75,02777778"
17,17,240206028,MUHAMMED YUSUF ALTUN,100,100,50,100,70,100,0,...,100,0,100,0,,60 NA,NA,NA,NA,"62,5"
18,18,240206031,HÜSEYİN KAAN TÜRK,100,100,100,100,100,100,25,...,100,30,100,50,100,60,50,80,90,"84,44444444"
19,19,240206043,ONAT OKKAOĞLU,100,100,0,100,100,100,90,...,40,20,100,70,100,40,70,0,100,"70,97222222"
20,20,240206047,ONURALP SÖZDİNLEROĞLU,100,90,100,100,100,100,30,...,100,20,100,50,100,70,70,20,100,"78,75"
21,21,240206048,KUBİLAY KABATAŞ,40,100,,,70,100,15,...,100,65,100,70,100 NA,,NA,30,100,"71,25"
22,22,240206052,HÜSEYİN ATA YILMAZÇELİK,40,100,100,100,85,100,10,...,100,75,100,50,100,100,100,0,60,"82,22222222"
23,23,240206053,AHMED BURAK GÜLTEKİN,100,100,0,100,100,100,20,...,100,30,100,70,100,60,,70 NA,NA,"74,86111111"
24,24,240206103,HALİL İBRAHİM ALKAN,NA,100,0,80,55,30,30,...,NA,15,95,50,60,30,70,0,100,"49,58333333"
25,25,240206131,YİĞİTCAN DİRİK,40,100,50,100,25,100,20,...,100,5,100,20,100,10,100,0,60,"72,77777778"
26,26,240206157,ÖYKÜ ATCI,NA,NA,NA,NA,5,30,0,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,"2,638888889"
27,27,240206176,OKAN GÖKALP,45,100,50,100,30,100,1,...,100,0,100,20,,60 NA,NA,75,100,"67,41666667"
28,28,250206001,AHMET YASİN BULUT,100,100,100,100,70,100,90,...,100,45,100,90,100,90,70,30,100,"85,83333333"
29,29,250206002,ESİN DUYGU ÖZDEMİR,40,100,50,100,40,100,0,...,,50 NA,100,90,100,10,70,30,100,"69,75"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,69,250206052,GAMZE AYTEKİN,50,100,100,100,100,100,55,...,100,15,90,40,55,80,70,20,100,"74,16666667"
70,70,250206053,ÖZGÜR DEMİR,100,100,100,100,80,100,10,...,100,65,100,20,100,60,70,50,95,"81,94444444"
71,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
72,71,250206054,ALAATTİN ÇAKIRLAR,30,100,0,100,5,100,10,...,100 NA,,NA,0,100,35,70,0,70,"58,08333333"
73,72,250206055,AHMET YILMAZ,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
74,73,250206056,EGE AYDENİZ,100,100,100,70,0,100,0,...,30,0,100,0,90,1,,70 NA,NA,"60,61111111"
75,74,250206057,KADİR GÜRHAN KAYA,100,100,100,90,90,100,90,...,100,70,100,30,100,80,70,60,100,"87,22222222"
76,75,250206058,SEBAHATTİN YARICI,100,90,100,100,65,85,10,...,85,50,100,0,100,80,70,80,90,81
77,76,250206059,ÇAĞLA KARAHAN,100,100,50,100,100,100,45,...,100,100,100,90,100,80,70,20,85,"82,11111111"
78,77,250206060,MUHAMMED ALİ ŞAHİN,30,90,0,85,68,90,55,...,100,15,50,40,60,30,70,75,100,"70,36111111"
79,78,250206062,UTKU ACAR,100,100,100,100,100,100,50,...,100,40,100,70,100,85,70,50,100,"86,25"
80,79,250206073,BARIŞ BERKE ÇAĞLAR,100,90,100,100,50,100,25,...,100,100,90,0,95,100,70,50,100,"83,33333333"
81,80,250206076,ASİYE KURCAK,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
82,81,250206079,BERKAY ARPAT,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
83,82,250206081,CEM KARAGÖZ,100,100,100,90,70,100,80,...,100,0,70,30,60,70,40,20,100,70
84,83,250206082,ÖZCAN GEDİK,100,100,100,90,70,100,80,...,100 NA,,NA,NA,NA,NA,NA,NA,NA,"50,58333333"
85,84,250206083,EMRE GARİP,50,100,100,100,100,60,70,...,100,55,90,40,100,45,100,50,100,"80,97222222"
86,85,250206084,İZZET KALDAN,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
87,86,260206003,CEYHUN EFE KAYAN,50,100,100,100,95,100,70,...,100,30,100,60,100 NA,,NA,50,85,"75,41666667"
88,87,260206005,EGE GENİŞOĞLU,70,100,100,30,50,80,10,...,100,0,100,30,100,1,40,0,50,"61,55555556"
89,88,260206008,BARIŞ DENİZ GÖKMEN,100,100,100,100,88,60,85,...,100,50,90,40,100,45,100,80,100,"85,52777778"
90,89,260206018,ENES TÜFEKCİ,70,85,100,100,90,90,15,...,0,0,70,30,60,75,,40 NA,NA,56
91,90,260206019,ARDA SEVİNÇ,100,100,100,100,0,100,65,...,100,30,100,30,100,80,70,50,85,"81,52777778"
92,91,260206040,YAĞIZ TİRYAKİ,70,90,100,30,45,80,10,...,100,25,100,40,100,1,40,0,50,"61,55555556"
93,92,260206044,CAN KAYAN,20,75,0,100,20,90,10,...,,0 NA,100 NA,,,30 NA,NA,NA,NA,"42,63888889"
94,93,260206050,OKAN KARA,100,100,100,100,23,100,50,...,90,20,100,60,100,70,70,0,30,"70,94444444"
95,94,260206074,CELİL YILMAZ,100,90,100,85,100,90,60,...,100,30,50,20,60,95,70,40,100,75
96,95,260206075,MERT BURAK YASDIKCIOĞLU,70,100,100,100,25,100,45,...,,90 NA,NA,NA,NA,NA,NA,NA,NA,"47,63888889"
97,96,260206077,ZEYNEP GENİM,30,100,100,100,40,100,25,...,,90 NA,NA,40,70,10,70,0,100,"59,33333333"
98,97,260206079,MUTLU TAŞYER,30,100,100,100,90,90,10,...,100,10,100,0,100,30,,70 NA,NA,"70,86111111"

In [32]:
df_lab1.drop(0, axis=0, inplace=True)
df_lab1.drop('#', index=1, inplace=True)

ValueError: Cannot specify both 'labels' and 'index'/'columns'

In [33]:
df_lab1.drop(0, axis=0, inplace=True)
df_lab1.drop('#', axis=1, inplace=True)

KeyError: '[0] not found in axis'

In [34]:
df_lab1

,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
1,1,210206004,MUHAMMET ÇİFTÇİ,100,90,,,30,100,20,...,100,,100 NA,,NA,NA,NA,NA,NA,45
2,2,210206040,FERHAT TEMÜR,70,100,100,100,100,100,90,...,100,65,100 NA,,NA,40,0,0,90,"62,94444444"
3,3,220206017,LÜTFİ DİNÇ,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
4,4,220206047,ERDOĞAN FİDAN,100,90,0,100,70,100,5,...,100,0,100 NA,,NA,NA,NA,NA,NA,"54,02777778"
5,5,230206003,AHMET DALGIÇ,100,90,100,100,100,100,30,...,100,0,100,50,100,40,70,0,100,"76,38888889"
6,6,230206007,ENGİN YUNUS GÜNER,100,100,100,100,40,100,80,...,100,75,100,50,100,100,80,50,100,"88,47222222"
7,7,230206012,EGEMEN ÖZKAYA,100,100,100,100,100,100,40,...,100,65,100,40,60,85,70,0,100,"78,33333333"
8,8,230206023,YİĞİT VATANSEVER,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
9,9,230206031,ONUR METE,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
10,10,230206046,EKİN ERİŞ,100,100,100,100,100,100,90,...,100,30,100,50,60,60,70,0,100,"75,69444444"
11,11,230206057,EFE KOCATAŞ,100,100,50,100,100,100,90,...,100,45,100,60,60,100,70,50,90,"81,66666667"
12,12,240206004,MİRZA FETHULLAH YARAN,100,100,100,100 NA,,NA,80,...,100,30,100,70,60,50,70,50,100,"70,02777778"
13,13,240206011,HAKAN AKAR,100,100,100,100,100,100,90,...,40,100,100,85,100,75,70,30,100,"82,77777778"
14,14,240206023,ZEHRA DENİZ SALMAN,100,100,50,100,100,100,70,...,100,60,100,80,100,100,70,20,85,"84,72222222"
15,15,240206025,ONUR TÜRKMEN,100,80,100,100,100,100,60,...,100,30,100,90,100,100,70,70,100,"88,88888889"
16,16,240206026,VOLKAN DEDE,70,100,50,100,10,100,35,...,100,15,100,40,100,30,50,50,90,"75,02777778"
17,17,240206028,MUHAMMED YUSUF ALTUN,100,100,50,100,70,100,0,...,100,0,100,0,,60 NA,NA,NA,NA,"62,5"
18,18,240206031,HÜSEYİN KAAN TÜRK,100,100,100,100,100,100,25,...,100,30,100,50,100,60,50,80,90,"84,44444444"
19,19,240206043,ONAT OKKAOĞLU,100,100,0,100,100,100,90,...,40,20,100,70,100,40,70,0,100,"70,97222222"
20,20,240206047,ONURALP SÖZDİNLEROĞLU,100,90,100,100,100,100,30,...,100,20,100,50,100,70,70,20,100,"78,75"
21,21,240206048,KUBİLAY KABATAŞ,40,100,,,70,100,15,...,100,65,100,70,100 NA,,NA,30,100,"71,25"
22,22,240206052,HÜSEYİN ATA YILMAZÇELİK,40,100,100,100,85,100,10,...,100,75,100,50,100,100,100,0,60,"82,22222222"
23,23,240206053,AHMED BURAK GÜLTEKİN,100,100,0,100,100,100,20,...,100,30,100,70,100,60,,70 NA,NA,"74,86111111"
24,24,240206103,HALİL İBRAHİM ALKAN,NA,100,0,80,55,30,30,...,NA,15,95,50,60,30,70,0,100,"49,58333333"
25,25,240206131,YİĞİTCAN DİRİK,40,100,50,100,25,100,20,...,100,5,100,20,100,10,100,0,60,"72,77777778"
26,26,240206157,ÖYKÜ ATCI,NA,NA,NA,NA,5,30,0,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,"2,638888889"
27,27,240206176,OKAN GÖKALP,45,100,50,100,30,100,1,...,100,0,100,20,,60 NA,NA,75,100,"67,41666667"
28,28,250206001,AHMET YASİN BULUT,100,100,100,100,70,100,90,...,100,45,100,90,100,90,70,30,100,"85,83333333"
29,29,250206002,ESİN DUYGU ÖZDEMİR,40,100,50,100,40,100,0,...,,50 NA,100,90,100,10,70,30,100,"69,75"
30,30,250206004,BARBAROS İNAK,100,100,50,100,100,100,70,...,100,30,100,90,100,100,90,75,100,"89,44444444"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,69,250206052,GAMZE AYTEKİN,50,100,100,100,100,100,55,...,100,15,90,40,55,80,70,20,100,"74,16666667"
70,70,250206053,ÖZGÜR DEMİR,100,100,100,100,80,100,10,...,100,65,100,20,100,60,70,50,95,"81,94444444"
71,#,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
72,71,250206054,ALAATTİN ÇAKIRLAR,30,100,0,100,5,100,10,...,100 NA,,NA,0,100,35,70,0,70,"58,08333333"
73,72,250206055,AHMET YILMAZ,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
74,73,250206056,EGE AYDENİZ,100,100,100,70,0,100,0,...,30,0,100,0,90,1,,70 NA,NA,"60,61111111"
75,74,250206057,KADİR GÜRHAN KAYA,100,100,100,90,90,100,90,...,100,70,100,30,100,80,70,60,100,"87,22222222"
76,75,250206058,SEBAHATTİN YARICI,100,90,100,100,65,85,10,...,85,50,100,0,100,80,70,80,90,81
77,76,250206059,ÇAĞLA KARAHAN,100,100,50,100,100,100,45,...,100,100,100,90,100,80,70,20,85,"82,11111111"
78,77,250206060,MUHAMMED ALİ ŞAHİN,30,90,0,85,68,90,55,...,100,15,50,40,60,30,70,75,100,"70,36111111"
79,78,250206062,UTKU ACAR,100,100,100,100,100,100,50,...,100,40,100,70,100,85,70,50,100,"86,25"
80,79,250206073,BARIŞ BERKE ÇAĞLAR,100,90,100,100,50,100,25,...,100,100,90,0,95,100,70,50,100,"83,33333333"
81,80,250206076,ASİYE KURCAK,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
82,81,250206079,BERKAY ARPAT,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
83,82,250206081,CEM KARAGÖZ,100,100,100,90,70,100,80,...,100,0,70,30,60,70,40,20,100,70
84,83,250206082,ÖZCAN GEDİK,100,100,100,90,70,100,80,...,100 NA,,NA,NA,NA,NA,NA,NA,NA,"50,58333333"
85,84,250206083,EMRE GARİP,50,100,100,100,100,60,70,...,100,55,90,40,100,45,100,50,100,"80,97222222"
86,85,250206084,İZZET KALDAN,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
87,86,260206003,CEYHUN EFE KAYAN,50,100,100,100,95,100,70,...,100,30,100,60,100 NA,,NA,50,85,"75,41666667"
88,87,260206005,EGE GENİŞOĞLU,70,100,100,30,50,80,10,...,100,0,100,30,100,1,40,0,50,"61,55555556"
89,88,260206008,BARIŞ DENİZ GÖKMEN,100,100,100,100,88,60,85,...,100,50,90,40,100,45,100,80,100,"85,52777778"
90,89,260206018,ENES TÜFEKCİ,70,85,100,100,90,90,15,...,0,0,70,30,60,75,,40 NA,NA,56
91,90,260206019,ARDA SEVİNÇ,100,100,100,100,0,100,65,...,100,30,100,30,100,80,70,50,85,"81,52777778"
92,91,260206040,YAĞIZ TİRYAKİ,70,90,100,30,45,80,10,...,100,25,100,40,100,1,40,0,50,"61,55555556"
93,92,260206044,CAN KAYAN,20,75,0,100,20,90,10,...,,0 NA,100 NA,,,30 NA,NA,NA,NA,"42,63888889"
94,93,260206050,OKAN KARA,100,100,100,100,23,100,50,...,90,20,100,60,100,70,70,0,30,"70,94444444"
95,94,260206074,CELİL YILMAZ,100,90,100,85,100,90,60,...,100,30,50,20,60,95,70,40,100,75
96,95,260206075,MERT BURAK YASDIKCIOĞLU,70,100,100,100,25,100,45,...,,90 NA,NA,NA,NA,NA,NA,NA,NA,"47,63888889"
97,96,260206077,ZEYNEP GENİM,30,100,100,100,40,100,25,...,,90 NA,NA,40,70,10,70,0,100,"59,33333333"
98,97,260206079,MUTLU TAŞYER,30,100,100,100,90,90,10,...,100,10,100,0,100,30,,70 NA,NA,"70,86111111"

In [35]:
df_lab1.reset_index(drop=True, inplace=True)
df_lab1.drop('#', axis=1, inplace=True)

In [36]:
df_lab1

,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,Lab. Perf.-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
0,210206004,MUHAMMET ÇİFTÇİ,100,90,,,30,100,20,100,...,100,,100 NA,,NA,NA,NA,NA,NA,45
1,210206040,FERHAT TEMÜR,70,100,100,100,100,100,90,100,...,100,65,100 NA,,NA,40,0,0,90,"62,94444444"
2,220206017,LÜTFİ DİNÇ,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
3,220206047,ERDOĞAN FİDAN,100,90,0,100,70,100,5,100,...,100,0,100 NA,,NA,NA,NA,NA,NA,"54,02777778"
4,230206003,AHMET DALGIÇ,100,90,100,100,100,100,30,100,...,100,0,100,50,100,40,70,0,100,"76,38888889"
5,230206007,ENGİN YUNUS GÜNER,100,100,100,100,40,100,80,100,...,100,75,100,50,100,100,80,50,100,"88,47222222"
6,230206012,EGEMEN ÖZKAYA,100,100,100,100,100,100,40,100,...,100,65,100,40,60,85,70,0,100,"78,33333333"
7,230206023,YİĞİT VATANSEVER,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
8,230206031,ONUR METE,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
9,230206046,EKİN ERİŞ,100,100,100,100,100,100,90,100,...,100,30,100,50,60,60,70,0,100,"75,69444444"
10,230206057,EFE KOCATAŞ,100,100,50,100,100,100,90,100,...,100,45,100,60,60,100,70,50,90,"81,66666667"
11,240206004,MİRZA FETHULLAH YARAN,100,100,100,100 NA,,NA,80,100,...,100,30,100,70,60,50,70,50,100,"70,02777778"
12,240206011,HAKAN AKAR,100,100,100,100,100,100,90,100,...,40,100,100,85,100,75,70,30,100,"82,77777778"
13,240206023,ZEHRA DENİZ SALMAN,100,100,50,100,100,100,70,100,...,100,60,100,80,100,100,70,20,85,"84,72222222"
14,240206025,ONUR TÜRKMEN,100,80,100,100,100,100,60,100,...,100,30,100,90,100,100,70,70,100,"88,88888889"
15,240206026,VOLKAN DEDE,70,100,50,100,10,100,35,100,...,100,15,100,40,100,30,50,50,90,"75,02777778"
16,240206028,MUHAMMED YUSUF ALTUN,100,100,50,100,70,100,0,100,...,100,0,100,0,,60 NA,NA,NA,NA,"62,5"
17,240206031,HÜSEYİN KAAN TÜRK,100,100,100,100,100,100,25,100,...,100,30,100,50,100,60,50,80,90,"84,44444444"
18,240206043,ONAT OKKAOĞLU,100,100,0,100,100,100,90,100,...,40,20,100,70,100,40,70,0,100,"70,97222222"
19,240206047,ONURALP SÖZDİNLEROĞLU,100,90,100,100,100,100,30,100,...,100,20,100,50,100,70,70,20,100,"78,75"
20,240206048,KUBİLAY KABATAŞ,40,100,,,70,100,15,100,...,100,65,100,70,100 NA,,NA,30,100,"71,25"
21,240206052,HÜSEYİN ATA YILMAZÇELİK,40,100,100,100,85,100,10,100,...,100,75,100,50,100,100,100,0,60,"82,22222222"
22,240206053,AHMED BURAK GÜLTEKİN,100,100,0,100,100,100,20,100,...,100,30,100,70,100,60,,70 NA,NA,"74,86111111"
23,240206103,HALİL İBRAHİM ALKAN,NA,100,0,80,55,30,30,100,...,NA,15,95,50,60,30,70,0,100,"49,58333333"
24,240206131,YİĞİTCAN DİRİK,40,100,50,100,25,100,20,100,...,100,5,100,20,100,10,100,0,60,"72,77777778"
25,240206157,ÖYKÜ ATCI,NA,NA,NA,NA,5,30,0,0,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,"2,638888889"
26,240206176,OKAN GÖKALP,45,100,50,100,30,100,1,100,...,100,0,100,20,,60 NA,NA,75,100,"67,41666667"
27,250206001,AHMET YASİN BULUT,100,100,100,100,70,100,90,100,...,100,45,100,90,100,90,70,30,100,"85,83333333"
28,250206002,ESİN DUYGU ÖZDEMİR,40,100,50,100,40,100,0,100,...,,50 NA,100,90,100,10,70,30,100,"69,75"
29,250206004,BARBAROS İNAK,100,100,50,100,100,100,70,100,...,100,30,100,90,100,100,90,75,100,"89,44444444"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,250206052,GAMZE AYTEKİN,50,100,100,100,100,100,55,100,...,100,15,90,40,55,80,70,20,100,"74,16666667"
69,250206053,ÖZGÜR DEMİR,100,100,100,100,80,100,10,100,...,100,65,100,20,100,60,70,50,95,"81,94444444"
70,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,Lab. Perf.-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
71,250206054,ALAATTİN ÇAKIRLAR,30,100,0,100,5,100,10,100,...,100 NA,,NA,0,100,35,70,0,70,"58,08333333"
72,250206055,AHMET YILMAZ,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
73,250206056,EGE AYDENİZ,100,100,100,70,0,100,0,100,...,30,0,100,0,90,1,,70 NA,NA,"60,61111111"
74,250206057,KADİR GÜRHAN KAYA,100,100,100,90,90,100,90,100,...,100,70,100,30,100,80,70,60,100,"87,22222222"
75,250206058,SEBAHATTİN YARICI,100,90,100,100,65,85,10,100,...,85,50,100,0,100,80,70,80,90,81
76,250206059,ÇAĞLA KARAHAN,100,100,50,100,100,100,45,100,...,100,100,100,90,100,80,70,20,85,"82,11111111"
77,250206060,MUHAMMED ALİ ŞAHİN,30,90,0,85,68,90,55,100,...,100,15,50,40,60,30,70,75,100,"70,36111111"
78,250206062,UTKU ACAR,100,100,100,100,100,100,50,100,...,100,40,100,70,100,85,70,50,100,"86,25"
79,250206073,BARIŞ BERKE ÇAĞLAR,100,90,100,100,50,100,25,100,...,100,100,90,0,95,100,70,50,100,"83,33333333"
80,250206076,ASİYE KURCAK,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
81,250206079,BERKAY ARPAT,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
82,250206081,CEM KARAGÖZ,100,100,100,90,70,100,80,100,...,100,0,70,30,60,70,40,20,100,70
83,250206082,ÖZCAN GEDİK,100,100,100,90,70,100,80,100,...,100 NA,,NA,NA,NA,NA,NA,NA,NA,"50,58333333"
84,250206083,EMRE GARİP,50,100,100,100,100,60,70,100,...,100,55,90,40,100,45,100,50,100,"80,97222222"
85,250206084,İZZET KALDAN,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
86,260206003,CEYHUN EFE KAYAN,50,100,100,100,95,100,70,100,...,100,30,100,60,100 NA,,NA,50,85,"75,41666667"
87,260206005,EGE GENİŞOĞLU,70,100,100,30,50,80,10,100,...,100,0,100,30,100,1,40,0,50,"61,55555556"
88,260206008,BARIŞ DENİZ GÖKMEN,100,100,100,100,88,60,85,100,...,100,50,90,40,100,45,100,80,100,"85,52777778"
89,260206018,ENES TÜFEKCİ,70,85,100,100,90,90,15,100,...,0,0,70,30,60,75,,40 NA,NA,56
90,260206019,ARDA SEVİNÇ,100,100,100,100,0,100,65,100,...,100,30,100,30,100,80,70,50,85,"81,52777778"
91,260206040,YAĞIZ TİRYAKİ,70,90,100,30,45,80,10,100,...,100,25,100,40,100,1,40,0,50,"61,55555556"
92,260206044,CAN KAYAN,20,75,0,100,20,90,10,100,...,,0 NA,100 NA,,,30 NA,NA,NA,NA,"42,63888889"
93,260206050,OKAN KARA,100,100,100,100,23,100,50,50,...,90,20,100,60,100,70,70,0,30,"70,94444444"
94,260206074,CELİL YILMAZ,100,90,100,85,100,90,60,100,...,100,30,50,20,60,95,70,40,100,75
95,260206075,MERT BURAK YASDIKCIOĞLU,70,100,100,100,25,100,45,100,...,,90 NA,NA,NA,NA,NA,NA,NA,NA,"47,63888889"
96,260206077,ZEYNEP GENİM,30,100,100,100,40,100,25,100,...,,90 NA,NA,40,70,10,70,0,100,"59,33333333"
97,260206079,MUTLU TAŞYER,30,100,100,100,90,90,10,100,...,100,10,100,0,100,30,,70 NA,NA,"70,86111111"

In [37]:
df_lab1.at[11, 'Lab. Perf.-2']

'100 NA'

In [38]:
df_lab1.drop(70, axis=0, inplace=True)

In [39]:
df_lab1

,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,Lab. Perf.-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
0,210206004,MUHAMMET ÇİFTÇİ,100,90,,,30,100,20,100,...,100,,100 NA,,NA,NA,NA,NA,NA,45
1,210206040,FERHAT TEMÜR,70,100,100,100,100,100,90,100,...,100,65,100 NA,,NA,40,0,0,90,"62,94444444"
2,220206017,LÜTFİ DİNÇ,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
3,220206047,ERDOĞAN FİDAN,100,90,0,100,70,100,5,100,...,100,0,100 NA,,NA,NA,NA,NA,NA,"54,02777778"
4,230206003,AHMET DALGIÇ,100,90,100,100,100,100,30,100,...,100,0,100,50,100,40,70,0,100,"76,38888889"
5,230206007,ENGİN YUNUS GÜNER,100,100,100,100,40,100,80,100,...,100,75,100,50,100,100,80,50,100,"88,47222222"
6,230206012,EGEMEN ÖZKAYA,100,100,100,100,100,100,40,100,...,100,65,100,40,60,85,70,0,100,"78,33333333"
7,230206023,YİĞİT VATANSEVER,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
8,230206031,ONUR METE,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
9,230206046,EKİN ERİŞ,100,100,100,100,100,100,90,100,...,100,30,100,50,60,60,70,0,100,"75,69444444"
10,230206057,EFE KOCATAŞ,100,100,50,100,100,100,90,100,...,100,45,100,60,60,100,70,50,90,"81,66666667"
11,240206004,MİRZA FETHULLAH YARAN,100,100,100,100 NA,,NA,80,100,...,100,30,100,70,60,50,70,50,100,"70,02777778"
12,240206011,HAKAN AKAR,100,100,100,100,100,100,90,100,...,40,100,100,85,100,75,70,30,100,"82,77777778"
13,240206023,ZEHRA DENİZ SALMAN,100,100,50,100,100,100,70,100,...,100,60,100,80,100,100,70,20,85,"84,72222222"
14,240206025,ONUR TÜRKMEN,100,80,100,100,100,100,60,100,...,100,30,100,90,100,100,70,70,100,"88,88888889"
15,240206026,VOLKAN DEDE,70,100,50,100,10,100,35,100,...,100,15,100,40,100,30,50,50,90,"75,02777778"
16,240206028,MUHAMMED YUSUF ALTUN,100,100,50,100,70,100,0,100,...,100,0,100,0,,60 NA,NA,NA,NA,"62,5"
17,240206031,HÜSEYİN KAAN TÜRK,100,100,100,100,100,100,25,100,...,100,30,100,50,100,60,50,80,90,"84,44444444"
18,240206043,ONAT OKKAOĞLU,100,100,0,100,100,100,90,100,...,40,20,100,70,100,40,70,0,100,"70,97222222"
19,240206047,ONURALP SÖZDİNLEROĞLU,100,90,100,100,100,100,30,100,...,100,20,100,50,100,70,70,20,100,"78,75"
20,240206048,KUBİLAY KABATAŞ,40,100,,,70,100,15,100,...,100,65,100,70,100 NA,,NA,30,100,"71,25"
21,240206052,HÜSEYİN ATA YILMAZÇELİK,40,100,100,100,85,100,10,100,...,100,75,100,50,100,100,100,0,60,"82,22222222"
22,240206053,AHMED BURAK GÜLTEKİN,100,100,0,100,100,100,20,100,...,100,30,100,70,100,60,,70 NA,NA,"74,86111111"
23,240206103,HALİL İBRAHİM ALKAN,NA,100,0,80,55,30,30,100,...,NA,15,95,50,60,30,70,0,100,"49,58333333"
24,240206131,YİĞİTCAN DİRİK,40,100,50,100,25,100,20,100,...,100,5,100,20,100,10,100,0,60,"72,77777778"
25,240206157,ÖYKÜ ATCI,NA,NA,NA,NA,5,30,0,0,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,"2,638888889"
26,240206176,OKAN GÖKALP,45,100,50,100,30,100,1,100,...,100,0,100,20,,60 NA,NA,75,100,"67,41666667"
27,250206001,AHMET YASİN BULUT,100,100,100,100,70,100,90,100,...,100,45,100,90,100,90,70,30,100,"85,83333333"
28,250206002,ESİN DUYGU ÖZDEMİR,40,100,50,100,40,100,0,100,...,,50 NA,100,90,100,10,70,30,100,"69,75"
29,250206004,BARBAROS İNAK,100,100,50,100,100,100,70,100,...,100,30,100,90,100,100,90,75,100,"89,44444444"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,250206051,EGEMEN YAĞCI,70,75,0,100,20,100 NA,,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,"25,41666667"
68,250206052,GAMZE AYTEKİN,50,100,100,100,100,100,55,100,...,100,15,90,40,55,80,70,20,100,"74,16666667"
69,250206053,ÖZGÜR DEMİR,100,100,100,100,80,100,10,100,...,100,65,100,20,100,60,70,50,95,"81,94444444"
71,250206054,ALAATTİN ÇAKIRLAR,30,100,0,100,5,100,10,100,...,100 NA,,NA,0,100,35,70,0,70,"58,08333333"
72,250206055,AHMET YILMAZ,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
73,250206056,EGE AYDENİZ,100,100,100,70,0,100,0,100,...,30,0,100,0,90,1,,70 NA,NA,"60,61111111"
74,250206057,KADİR GÜRHAN KAYA,100,100,100,90,90,100,90,100,...,100,70,100,30,100,80,70,60,100,"87,22222222"
75,250206058,SEBAHATTİN YARICI,100,90,100,100,65,85,10,100,...,85,50,100,0,100,80,70,80,90,81
76,250206059,ÇAĞLA KARAHAN,100,100,50,100,100,100,45,100,...,100,100,100,90,100,80,70,20,85,"82,11111111"
77,250206060,MUHAMMED ALİ ŞAHİN,30,90,0,85,68,90,55,100,...,100,15,50,40,60,30,70,75,100,"70,36111111"
78,250206062,UTKU ACAR,100,100,100,100,100,100,50,100,...,100,40,100,70,100,85,70,50,100,"86,25"
79,250206073,BARIŞ BERKE ÇAĞLAR,100,90,100,100,50,100,25,100,...,100,100,90,0,95,100,70,50,100,"83,33333333"
80,250206076,ASİYE KURCAK,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
81,250206079,BERKAY ARPAT,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
82,250206081,CEM KARAGÖZ,100,100,100,90,70,100,80,100,...,100,0,70,30,60,70,40,20,100,70
83,250206082,ÖZCAN GEDİK,100,100,100,90,70,100,80,100,...,100 NA,,NA,NA,NA,NA,NA,NA,NA,"50,58333333"
84,250206083,EMRE GARİP,50,100,100,100,100,60,70,100,...,100,55,90,40,100,45,100,50,100,"80,97222222"
85,250206084,İZZET KALDAN,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
86,260206003,CEYHUN EFE KAYAN,50,100,100,100,95,100,70,100,...,100,30,100,60,100 NA,,NA,50,85,"75,41666667"
87,260206005,EGE GENİŞOĞLU,70,100,100,30,50,80,10,100,...,100,0,100,30,100,1,40,0,50,"61,55555556"
88,260206008,BARIŞ DENİZ GÖKMEN,100,100,100,100,88,60,85,100,...,100,50,90,40,100,45,100,80,100,"85,52777778"
89,260206018,ENES TÜFEKCİ,70,85,100,100,90,90,15,100,...,0,0,70,30,60,75,,40 NA,NA,56
90,260206019,ARDA SEVİNÇ,100,100,100,100,0,100,65,100,...,100,30,100,30,100,80,70,50,85,"81,52777778"
91,260206040,YAĞIZ TİRYAKİ,70,90,100,30,45,80,10,100,...,100,25,100,40,100,1,40,0,50,"61,55555556"
92,260206044,CAN KAYAN,20,75,0,100,20,90,10,100,...,,0 NA,100 NA,,,30 NA,NA,NA,NA,"42,63888889"
93,260206050,OKAN KARA,100,100,100,100,23,100,50,50,...,90,20,100,60,100,70,70,0,30,"70,94444444"
94,260206074,CELİL YILMAZ,100,90,100,85,100,90,60,100,...,100,30,50,20,60,95,70,40,100,75
95,260206075,MERT BURAK YASDIKCIOĞLU,70,100,100,100,25,100,45,100,...,,90 NA,NA,NA,NA,NA,NA,NA,NA,"47,63888889"
96,260206077,ZEYNEP GENİM,30,100,100,100,40,100,25,100,...,,90 NA,NA,40,70,10,70,0,100,"59,33333333"
97,260206079,MUTLU TAŞYER,30,100,100,100,90,90,10,100,...,100,10,100,0,100,30,,70 NA,NA,"70,86111111"

In [40]:
df_lab1.reset_index(drop=True, inplace=True)

In [41]:
df_lab1

,Student ID,Student Name,Quiz-1,Lab. Perf.-1,Quiz-2,Lab. Perf.-2,Quiz-3,Lab. Perf.-3,Quiz-4,Lab. Perf.-4,...,Lab. Perf.-5,Quiz-6,Lab. Perf.-6,Quiz-7,Lab. Perf.-7,Quiz-8,Lab. Perf.-8,Quiz-9,Lab. Perf.-9,Term Grade
0,210206004,MUHAMMET ÇİFTÇİ,100,90,,,30,100,20,100,...,100,,100 NA,,NA,NA,NA,NA,NA,45
1,210206040,FERHAT TEMÜR,70,100,100,100,100,100,90,100,...,100,65,100 NA,,NA,40,0,0,90,"62,94444444"
2,220206017,LÜTFİ DİNÇ,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
3,220206047,ERDOĞAN FİDAN,100,90,0,100,70,100,5,100,...,100,0,100 NA,,NA,NA,NA,NA,NA,"54,02777778"
4,230206003,AHMET DALGIÇ,100,90,100,100,100,100,30,100,...,100,0,100,50,100,40,70,0,100,"76,38888889"
5,230206007,ENGİN YUNUS GÜNER,100,100,100,100,40,100,80,100,...,100,75,100,50,100,100,80,50,100,"88,47222222"
6,230206012,EGEMEN ÖZKAYA,100,100,100,100,100,100,40,100,...,100,65,100,40,60,85,70,0,100,"78,33333333"
7,230206023,YİĞİT VATANSEVER,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
8,230206031,ONUR METE,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
9,230206046,EKİN ERİŞ,100,100,100,100,100,100,90,100,...,100,30,100,50,60,60,70,0,100,"75,69444444"
10,230206057,EFE KOCATAŞ,100,100,50,100,100,100,90,100,...,100,45,100,60,60,100,70,50,90,"81,66666667"
11,240206004,MİRZA FETHULLAH YARAN,100,100,100,100 NA,,NA,80,100,...,100,30,100,70,60,50,70,50,100,"70,02777778"
12,240206011,HAKAN AKAR,100,100,100,100,100,100,90,100,...,40,100,100,85,100,75,70,30,100,"82,77777778"
13,240206023,ZEHRA DENİZ SALMAN,100,100,50,100,100,100,70,100,...,100,60,100,80,100,100,70,20,85,"84,72222222"
14,240206025,ONUR TÜRKMEN,100,80,100,100,100,100,60,100,...,100,30,100,90,100,100,70,70,100,"88,88888889"
15,240206026,VOLKAN DEDE,70,100,50,100,10,100,35,100,...,100,15,100,40,100,30,50,50,90,"75,02777778"
16,240206028,MUHAMMED YUSUF ALTUN,100,100,50,100,70,100,0,100,...,100,0,100,0,,60 NA,NA,NA,NA,"62,5"
17,240206031,HÜSEYİN KAAN TÜRK,100,100,100,100,100,100,25,100,...,100,30,100,50,100,60,50,80,90,"84,44444444"
18,240206043,ONAT OKKAOĞLU,100,100,0,100,100,100,90,100,...,40,20,100,70,100,40,70,0,100,"70,97222222"
19,240206047,ONURALP SÖZDİNLEROĞLU,100,90,100,100,100,100,30,100,...,100,20,100,50,100,70,70,20,100,"78,75"
20,240206048,KUBİLAY KABATAŞ,40,100,,,70,100,15,100,...,100,65,100,70,100 NA,,NA,30,100,"71,25"
21,240206052,HÜSEYİN ATA YILMAZÇELİK,40,100,100,100,85,100,10,100,...,100,75,100,50,100,100,100,0,60,"82,22222222"
22,240206053,AHMED BURAK GÜLTEKİN,100,100,0,100,100,100,20,100,...,100,30,100,70,100,60,,70 NA,NA,"74,86111111"
23,240206103,HALİL İBRAHİM ALKAN,NA,100,0,80,55,30,30,100,...,NA,15,95,50,60,30,70,0,100,"49,58333333"
24,240206131,YİĞİTCAN DİRİK,40,100,50,100,25,100,20,100,...,100,5,100,20,100,10,100,0,60,"72,77777778"
25,240206157,ÖYKÜ ATCI,NA,NA,NA,NA,5,30,0,0,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,"2,638888889"
26,240206176,OKAN GÖKALP,45,100,50,100,30,100,1,100,...,100,0,100,20,,60 NA,NA,75,100,"67,41666667"
27,250206001,AHMET YASİN BULUT,100,100,100,100,70,100,90,100,...,100,45,100,90,100,90,70,30,100,"85,83333333"
28,250206002,ESİN DUYGU ÖZDEMİR,40,100,50,100,40,100,0,100,...,,50 NA,100,90,100,10,70,30,100,"69,75"
29,250206004,BARBAROS İNAK,100,100,50,100,100,100,70,100,...,100,30,100,90,100,100,90,75,100,"89,44444444"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,250206051,EGEMEN YAĞCI,70,75,0,100,20,100 NA,,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,"25,41666667"
68,250206052,GAMZE AYTEKİN,50,100,100,100,100,100,55,100,...,100,15,90,40,55,80,70,20,100,"74,16666667"
69,250206053,ÖZGÜR DEMİR,100,100,100,100,80,100,10,100,...,100,65,100,20,100,60,70,50,95,"81,94444444"
70,250206054,ALAATTİN ÇAKIRLAR,30,100,0,100,5,100,10,100,...,100 NA,,NA,0,100,35,70,0,70,"58,08333333"
71,250206055,AHMET YILMAZ,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
72,250206056,EGE AYDENİZ,100,100,100,70,0,100,0,100,...,30,0,100,0,90,1,,70 NA,NA,"60,61111111"
73,250206057,KADİR GÜRHAN KAYA,100,100,100,90,90,100,90,100,...,100,70,100,30,100,80,70,60,100,"87,22222222"
74,250206058,SEBAHATTİN YARICI,100,90,100,100,65,85,10,100,...,85,50,100,0,100,80,70,80,90,81
75,250206059,ÇAĞLA KARAHAN,100,100,50,100,100,100,45,100,...,100,100,100,90,100,80,70,20,85,"82,11111111"
76,250206060,MUHAMMED ALİ ŞAHİN,30,90,0,85,68,90,55,100,...,100,15,50,40,60,30,70,75,100,"70,36111111"
77,250206062,UTKU ACAR,100,100,100,100,100,100,50,100,...,100,40,100,70,100,85,70,50,100,"86,25"
78,250206073,BARIŞ BERKE ÇAĞLAR,100,90,100,100,50,100,25,100,...,100,100,90,0,95,100,70,50,100,"83,33333333"
79,250206076,ASİYE KURCAK,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
80,250206079,BERKAY ARPAT,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
81,250206081,CEM KARAGÖZ,100,100,100,90,70,100,80,100,...,100,0,70,30,60,70,40,20,100,70
82,250206082,ÖZCAN GEDİK,100,100,100,90,70,100,80,100,...,100 NA,,NA,NA,NA,NA,NA,NA,NA,"50,58333333"
83,250206083,EMRE GARİP,50,100,100,100,100,60,70,100,...,100,55,90,40,100,45,100,50,100,"80,97222222"
84,250206084,İZZET KALDAN,NA,NA,NA,NA,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,0
85,260206003,CEYHUN EFE KAYAN,50,100,100,100,95,100,70,100,...,100,30,100,60,100 NA,,NA,50,85,"75,41666667"
86,260206005,EGE GENİŞOĞLU,70,100,100,30,50,80,10,100,...,100,0,100,30,100,1,40,0,50,"61,55555556"
87,260206008,BARIŞ DENİZ GÖKMEN,100,100,100,100,88,60,85,100,...,100,50,90,40,100,45,100,80,100,"85,52777778"
88,260206018,ENES TÜFEKCİ,70,85,100,100,90,90,15,100,...,0,0,70,30,60,75,,40 NA,NA,56
89,260206019,ARDA SEVİNÇ,100,100,100,100,0,100,65,100,...,100,30,100,30,100,80,70,50,85,"81,52777778"
90,260206040,YAĞIZ TİRYAKİ,70,90,100,30,45,80,10,100,...,100,25,100,40,100,1,40,0,50,"61,55555556"
91,260206044,CAN KAYAN,20,75,0,100,20,90,10,100,...,,0 NA,100 NA,,,30 NA,NA,NA,NA,"42,63888889"
92,260206050,OKAN KARA,100,100,100,100,23,100,50,50,...,90,20,100,60,100,70,70,0,30,"70,94444444"
93,260206074,CELİL YILMAZ,100,90,100,85,100,90,60,100,...,100,30,50,20,60,95,70,40,100,75
94,260206075,MERT BURAK YASDIKCIOĞLU,70,100,100,100,25,100,45,100,...,,90 NA,NA,NA,NA,NA,NA,NA,NA,"47,63888889"
95,260206077,ZEYNEP GENİM,30,100,100,100,40,100,25,100,...,,90 NA,NA,40,70,10,70,0,100,"59,33333333"
96,260206079,MUTLU TAŞYER,30,100,100,100,90,90,10,100,...,100,10,100,0,100,30,,70 NA,NA,"70,86111111"

In [42]:
df

           ID  MIDTERM 1  MIDTERM 2  FINAL  LAB   ATTENDANCE  LETTER GRADE
0   210206004       24.0        0.0    NaN   NaN        0.45           NaN
1   210206040       62.0       25.0   65.0   NaN        0.60           NaN
2   220206017        NaN        NaN    NaN   NaN        0.00           NaN
3   220206047       46.0       45.0   28.0   NaN        0.65           NaN
4   230206003       29.0       40.0   24.0   NaN        0.70           NaN
5   230206007      100.0      100.0   63.0   NaN        1.00           NaN
6   230206012       83.0       95.0   85.0   NaN        0.80           NaN
7   230206023        NaN        NaN    NaN   NaN        0.00           NaN
8   230206031        NaN        NaN    NaN   NaN        0.00           NaN
9   230206046       81.0       70.0   60.0   NaN        1.00           NaN
10  230206057       48.0       60.0   32.0   NaN        0.90           NaN
11  240206004       55.0        4.0   31.0   NaN        0.45           NaN
12  240206011       82.0       95.0   56.0   NaN        0.60           NaN
13  240206023      100.0      105.0   81.0   NaN        1.00           NaN
14  240206025       84.0       70.0   71.0   NaN        0.60           NaN
15  240206026       58.0       13.0   41.0   NaN        0.75           NaN
16  240206028       37.0        0.0    NaN   NaN        0.45           NaN
17  240206031       49.0       50.0   57.0   NaN        0.70           NaN
18  240206043       56.0       30.0   40.0   NaN        0.95           NaN
19  240206047       63.0       30.0   53.0   NaN        0.90           NaN
20  240206048       66.0       15.0   36.0   NaN        0.65           NaN
21  240206052       26.0       35.0   24.0   NaN        0.80           NaN
22  240206053       74.0       45.0   40.0   NaN        0.65           NaN
23  240206103       54.0        5.0   31.0   NaN        0.75           NaN
24  240206131       17.0       40.0   19.0   NaN        0.85           NaN
25  240206157       14.0        NaN    NaN   NaN        0.00           NaN
26  240206176        8.0       17.0   12.0   NaN        0.60           NaN
27  250206001       95.0       65.0   64.0   NaN        0.85           NaN
28  250206002       56.0       20.0   67.0   NaN        0.85           NaN
29  250206004      100.0       95.0   54.0   NaN        1.00           NaN
..        ...        ...        ...    ...   ...         ...           ...
67  250206051        NaN        NaN    NaN   NaN        0.55           NaN
68  250206052       54.0      105.0   26.0   NaN        0.85           NaN
69  250206053       40.0       10.0   36.0   NaN        0.90           NaN
70  250206054       29.0       30.0   46.0   NaN        0.80           NaN
71  250206055        NaN        NaN    NaN   NaN        0.25           NaN
72  250206056       10.0        0.0    0.0   NaN        1.00           NaN
73  250206057       23.0       35.0   75.0   NaN        0.75           NaN
74  250206058       66.0       25.0   22.0   NaN        0.85           NaN
75  250206059       44.0       35.0   69.0   NaN        0.85           NaN
76  250206060       58.0       60.0   33.0   NaN        0.90           NaN
77  250206062       89.0       73.0   21.0   NaN        0.90           NaN
78  250206073       72.0       45.0   25.0   NaN        0.70           NaN
79  250206076        NaN        NaN    NaN   NaN        0.05           NaN
80  250206079        NaN        NaN    NaN   NaN        0.05           NaN
81  250206081       39.0       20.0    8.0   NaN        0.95           NaN
82  250206082       52.0        NaN    NaN   NaN        0.65           NaN
83  250206083       21.0        0.0   10.0   NaN        0.90           NaN
84  250206084        NaN        NaN    NaN   NaN        0.05           NaN
85  260206003       88.0       43.0   58.0   NaN        1.00           NaN
86  260206005        8.0       15.0   12.0   NaN        0.70           NaN
87  260206008       70.0       25.0   24.0   NaN        0.95           NaN
88  260206018       39.0        5.0    NaN   NaN        0.70           NaN
89  260206019       37.0        5.0   53.0   NaN        0.70           NaN
90  260206040       19.0       25.0   13.0   NaN        0.90           NaN
91  260206044       21.0        0.0    NaN   NaN        0.65           NaN
92  260206050       22.0       40.0   32.0   NaN        0.45           NaN
93  260206074       94.0       88.0   40.0   NaN        1.00           NaN
94  260206075       20.0        NaN    NaN   NaN        0.40           NaN
95  260206077       33.0       13.0    NaN   NaN        0.80           NaN
96  260206079        0.0        0.0    NaN   NaN        0.80           NaN

[97 rows x 7 columns]

In [43]:
df['LAB'] = df_lab1['Term Grade']

In [44]:
df

,ID,MIDTERM 1,MIDTERM 2,FINAL,LAB,ATTENDANCE,LETTER GRADE,LAB
0,210206004,24.0,0.0,NaN,NaN,0.45,NaN,45
1,210206040,62.0,25.0,65.0,NaN,0.60,NaN,"62,94444444"
2,220206017,NaN,NaN,NaN,NaN,0.00,NaN,0
3,220206047,46.0,45.0,28.0,NaN,0.65,NaN,"54,02777778"
4,230206003,29.0,40.0,24.0,NaN,0.70,NaN,"76,38888889"
5,230206007,100.0,100.0,63.0,NaN,1.00,NaN,"88,47222222"
6,230206012,83.0,95.0,85.0,NaN,0.80,NaN,"78,33333333"
7,230206023,NaN,NaN,NaN,NaN,0.00,NaN,0
8,230206031,NaN,NaN,NaN,NaN,0.00,NaN,0
9,230206046,81.0,70.0,60.0,NaN,1.00,NaN,"75,69444444"
10,230206057,48.0,60.0,32.0,NaN,0.90,NaN,"81,66666667"
11,240206004,55.0,4.0,31.0,NaN,0.45,NaN,"70,02777778"
12,240206011,82.0,95.0,56.0,NaN,0.60,NaN,"82,77777778"
13,240206023,100.0,105.0,81.0,NaN,1.00,NaN,"84,72222222"
14,240206025,84.0,70.0,71.0,NaN,0.60,NaN,"88,88888889"
15,240206026,58.0,13.0,41.0,NaN,0.75,NaN,"75,02777778"
16,240206028,37.0,0.0,NaN,NaN,0.45,NaN,"62,5"
17,240206031,49.0,50.0,57.0,NaN,0.70,NaN,"84,44444444"
18,240206043,56.0,30.0,40.0,NaN,0.95,NaN,"70,97222222"
19,240206047,63.0,30.0,53.0,NaN,0.90,NaN,"78,75"
20,240206048,66.0,15.0,36.0,NaN,0.65,NaN,"71,25"
21,240206052,26.0,35.0,24.0,NaN,0.80,NaN,"82,22222222"
22,240206053,74.0,45.0,40.0,NaN,0.65,NaN,"74,86111111"
23,240206103,54.0,5.0,31.0,NaN,0.75,NaN,"49,58333333"
24,240206131,17.0,40.0,19.0,NaN,0.85,NaN,"72,77777778"
25,240206157,14.0,NaN,NaN,NaN,0.00,NaN,"2,638888889"
26,240206176,8.0,17.0,12.0,NaN,0.60,NaN,"67,41666667"
27,250206001,95.0,65.0,64.0,NaN,0.85,NaN,"85,83333333"
28,250206002,56.0,20.0,67.0,NaN,0.85,NaN,"69,75"
29,250206004,100.0,95.0,54.0,NaN,1.00,NaN,"89,44444444"
...,...,...,...,...,...,...,...,...
67,250206051,NaN,NaN,NaN,NaN,0.55,NaN,"25,41666667"
68,250206052,54.0,105.0,26.0,NaN,0.85,NaN,"74,16666667"
69,250206053,40.0,10.0,36.0,NaN,0.90,NaN,"81,94444444"
70,250206054,29.0,30.0,46.0,NaN,0.80,NaN,"58,08333333"
71,250206055,NaN,NaN,NaN,NaN,0.25,NaN,0
72,250206056,10.0,0.0,0.0,NaN,1.00,NaN,"60,61111111"
73,250206057,23.0,35.0,75.0,NaN,0.75,NaN,"87,22222222"
74,250206058,66.0,25.0,22.0,NaN,0.85,NaN,81
75,250206059,44.0,35.0,69.0,NaN,0.85,NaN,"82,11111111"
76,250206060,58.0,60.0,33.0,NaN,0.90,NaN,"70,36111111"
77,250206062,89.0,73.0,21.0,NaN,0.90,NaN,"86,25"
78,250206073,72.0,45.0,25.0,NaN,0.70,NaN,"83,33333333"
79,250206076,NaN,NaN,NaN,NaN,0.05,NaN,0
80,250206079,NaN,NaN,NaN,NaN,0.05,NaN,0
81,250206081,39.0,20.0,8.0,NaN,0.95,NaN,70
82,250206082,52.0,NaN,NaN,NaN,0.65,NaN,"50,58333333"
83,250206083,21.0,0.0,10.0,NaN,0.90,NaN,"80,97222222"
84,250206084,NaN,NaN,NaN,NaN,0.05,NaN,0
85,260206003,88.0,43.0,58.0,NaN,1.00,NaN,"75,41666667"
86,260206005,8.0,15.0,12.0,NaN,0.70,NaN,"61,55555556"
87,260206008,70.0,25.0,24.0,NaN,0.95,NaN,"85,52777778"
88,260206018,39.0,5.0,NaN,NaN,0.70,NaN,56
89,260206019,37.0,5.0,53.0,NaN,0.70,NaN,"81,52777778"
90,260206040,19.0,25.0,13.0,NaN,0.90,NaN,"61,55555556"
91,260206044,21.0,0.0,NaN,NaN,0.65,NaN,"42,63888889"
92,260206050,22.0,40.0,32.0,NaN,0.45,NaN,"70,94444444"
93,260206074,94.0,88.0,40.0,NaN,1.00,NaN,75
94,260206075,20.0,NaN,NaN,NaN,0.40,NaN,"47,63888889"
95,260206077,33.0,13.0,NaN,NaN,0.80,NaN,"59,33333333"
96,260206079,0.0,0.0,NaN,NaN,0.80,NaN,"70,86111111"

In [45]:
df2 = df.drop('LAB', axis=1)

In [46]:
df2

           ID  MIDTERM 1  MIDTERM 2  FINAL  LAB   ATTENDANCE  LETTER GRADE
0   210206004       24.0        0.0    NaN   NaN        0.45           NaN
1   210206040       62.0       25.0   65.0   NaN        0.60           NaN
2   220206017        NaN        NaN    NaN   NaN        0.00           NaN
3   220206047       46.0       45.0   28.0   NaN        0.65           NaN
4   230206003       29.0       40.0   24.0   NaN        0.70           NaN
5   230206007      100.0      100.0   63.0   NaN        1.00           NaN
6   230206012       83.0       95.0   85.0   NaN        0.80           NaN
7   230206023        NaN        NaN    NaN   NaN        0.00           NaN
8   230206031        NaN        NaN    NaN   NaN        0.00           NaN
9   230206046       81.0       70.0   60.0   NaN        1.00           NaN
10  230206057       48.0       60.0   32.0   NaN        0.90           NaN
11  240206004       55.0        4.0   31.0   NaN        0.45           NaN
12  240206011       82.0       95.0   56.0   NaN        0.60           NaN
13  240206023      100.0      105.0   81.0   NaN        1.00           NaN
14  240206025       84.0       70.0   71.0   NaN        0.60           NaN
15  240206026       58.0       13.0   41.0   NaN        0.75           NaN
16  240206028       37.0        0.0    NaN   NaN        0.45           NaN
17  240206031       49.0       50.0   57.0   NaN        0.70           NaN
18  240206043       56.0       30.0   40.0   NaN        0.95           NaN
19  240206047       63.0       30.0   53.0   NaN        0.90           NaN
20  240206048       66.0       15.0   36.0   NaN        0.65           NaN
21  240206052       26.0       35.0   24.0   NaN        0.80           NaN
22  240206053       74.0       45.0   40.0   NaN        0.65           NaN
23  240206103       54.0        5.0   31.0   NaN        0.75           NaN
24  240206131       17.0       40.0   19.0   NaN        0.85           NaN
25  240206157       14.0        NaN    NaN   NaN        0.00           NaN
26  240206176        8.0       17.0   12.0   NaN        0.60           NaN
27  250206001       95.0       65.0   64.0   NaN        0.85           NaN
28  250206002       56.0       20.0   67.0   NaN        0.85           NaN
29  250206004      100.0       95.0   54.0   NaN        1.00           NaN
..        ...        ...        ...    ...   ...         ...           ...
67  250206051        NaN        NaN    NaN   NaN        0.55           NaN
68  250206052       54.0      105.0   26.0   NaN        0.85           NaN
69  250206053       40.0       10.0   36.0   NaN        0.90           NaN
70  250206054       29.0       30.0   46.0   NaN        0.80           NaN
71  250206055        NaN        NaN    NaN   NaN        0.25           NaN
72  250206056       10.0        0.0    0.0   NaN        1.00           NaN
73  250206057       23.0       35.0   75.0   NaN        0.75           NaN
74  250206058       66.0       25.0   22.0   NaN        0.85           NaN
75  250206059       44.0       35.0   69.0   NaN        0.85           NaN
76  250206060       58.0       60.0   33.0   NaN        0.90           NaN
77  250206062       89.0       73.0   21.0   NaN        0.90           NaN
78  250206073       72.0       45.0   25.0   NaN        0.70           NaN
79  250206076        NaN        NaN    NaN   NaN        0.05           NaN
80  250206079        NaN        NaN    NaN   NaN        0.05           NaN
81  250206081       39.0       20.0    8.0   NaN        0.95           NaN
82  250206082       52.0        NaN    NaN   NaN        0.65           NaN
83  250206083       21.0        0.0   10.0   NaN        0.90           NaN
84  250206084        NaN        NaN    NaN   NaN        0.05           NaN
85  260206003       88.0       43.0   58.0   NaN        1.00           NaN
86  260206005        8.0       15.0   12.0   NaN        0.70           NaN
87  260206008       70.0       25.0   24.0   NaN        0.95           NaN
88  260206018       39.0        5.0    NaN   NaN        0.70           NaN
89  260206019       37.0        5.0   53.0   NaN        0.70           NaN
90  260206040       19.0       25.0   13.0   NaN        0.90           NaN
91  260206044       21.0        0.0    NaN   NaN        0.65           NaN
92  260206050       22.0       40.0   32.0   NaN        0.45           NaN
93  260206074       94.0       88.0   40.0   NaN        1.00           NaN
94  260206075       20.0        NaN    NaN   NaN        0.40           NaN
95  260206077       33.0       13.0    NaN   NaN        0.80           NaN
96  260206079        0.0        0.0    NaN   NaN        0.80           NaN

[97 rows x 7 columns]

In [48]:
df2.loc['LAB']

KeyError: 'LAB'

In [49]:
df2['LAB']

KeyError: 'LAB'

In [50]:
df2

           ID  MIDTERM 1  MIDTERM 2  FINAL  LAB   ATTENDANCE  LETTER GRADE
0   210206004       24.0        0.0    NaN   NaN        0.45           NaN
1   210206040       62.0       25.0   65.0   NaN        0.60           NaN
2   220206017        NaN        NaN    NaN   NaN        0.00           NaN
3   220206047       46.0       45.0   28.0   NaN        0.65           NaN
4   230206003       29.0       40.0   24.0   NaN        0.70           NaN
5   230206007      100.0      100.0   63.0   NaN        1.00           NaN
6   230206012       83.0       95.0   85.0   NaN        0.80           NaN
7   230206023        NaN        NaN    NaN   NaN        0.00           NaN
8   230206031        NaN        NaN    NaN   NaN        0.00           NaN
9   230206046       81.0       70.0   60.0   NaN        1.00           NaN
10  230206057       48.0       60.0   32.0   NaN        0.90           NaN
11  240206004       55.0        4.0   31.0   NaN        0.45           NaN
12  240206011       82.0       95.0   56.0   NaN        0.60           NaN
13  240206023      100.0      105.0   81.0   NaN        1.00           NaN
14  240206025       84.0       70.0   71.0   NaN        0.60           NaN
15  240206026       58.0       13.0   41.0   NaN        0.75           NaN
16  240206028       37.0        0.0    NaN   NaN        0.45           NaN
17  240206031       49.0       50.0   57.0   NaN        0.70           NaN
18  240206043       56.0       30.0   40.0   NaN        0.95           NaN
19  240206047       63.0       30.0   53.0   NaN        0.90           NaN
20  240206048       66.0       15.0   36.0   NaN        0.65           NaN
21  240206052       26.0       35.0   24.0   NaN        0.80           NaN
22  240206053       74.0       45.0   40.0   NaN        0.65           NaN
23  240206103       54.0        5.0   31.0   NaN        0.75           NaN
24  240206131       17.0       40.0   19.0   NaN        0.85           NaN
25  240206157       14.0        NaN    NaN   NaN        0.00           NaN
26  240206176        8.0       17.0   12.0   NaN        0.60           NaN
27  250206001       95.0       65.0   64.0   NaN        0.85           NaN
28  250206002       56.0       20.0   67.0   NaN        0.85           NaN
29  250206004      100.0       95.0   54.0   NaN        1.00           NaN
..        ...        ...        ...    ...   ...         ...           ...
67  250206051        NaN        NaN    NaN   NaN        0.55           NaN
68  250206052       54.0      105.0   26.0   NaN        0.85           NaN
69  250206053       40.0       10.0   36.0   NaN        0.90           NaN
70  250206054       29.0       30.0   46.0   NaN        0.80           NaN
71  250206055        NaN        NaN    NaN   NaN        0.25           NaN
72  250206056       10.0        0.0    0.0   NaN        1.00           NaN
73  250206057       23.0       35.0   75.0   NaN        0.75           NaN
74  250206058       66.0       25.0   22.0   NaN        0.85           NaN
75  250206059       44.0       35.0   69.0   NaN        0.85           NaN
76  250206060       58.0       60.0   33.0   NaN        0.90           NaN
77  250206062       89.0       73.0   21.0   NaN        0.90           NaN
78  250206073       72.0       45.0   25.0   NaN        0.70           NaN
79  250206076        NaN        NaN    NaN   NaN        0.05           NaN
80  250206079        NaN        NaN    NaN   NaN        0.05           NaN
81  250206081       39.0       20.0    8.0   NaN        0.95           NaN
82  250206082       52.0        NaN    NaN   NaN        0.65           NaN
83  250206083       21.0        0.0   10.0   NaN        0.90           NaN
84  250206084        NaN        NaN    NaN   NaN        0.05           NaN
85  260206003       88.0       43.0   58.0   NaN        1.00           NaN
86  260206005        8.0       15.0   12.0   NaN        0.70           NaN
87  260206008       70.0       25.0   24.0   NaN        0.95           NaN
88  260206018       39.0        5.0    NaN   NaN        0.70           NaN
89  260206019       37.0        5.0   53.0   NaN        0.70           NaN
90  260206040       19.0       25.0   13.0   NaN        0.90           NaN
91  260206044       21.0        0.0    NaN   NaN        0.65           NaN
92  260206050       22.0       40.0   32.0   NaN        0.45           NaN
93  260206074       94.0       88.0   40.0   NaN        1.00           NaN
94  260206075       20.0        NaN    NaN   NaN        0.40           NaN
95  260206077       33.0       13.0    NaN   NaN        0.80           NaN
96  260206079        0.0        0.0    NaN   NaN        0.80           NaN

[97 rows x 7 columns]

In [51]:
df2.drop('LAB', axis=1, inplace=True)

KeyError: "['LAB'] not found in axis"

In [52]:
df2.colums()

AttributeError: 'DataFrame' object has no attribute 'colums'

In [53]:
df2.columns

Index(['ID', 'MIDTERM 1', 'MIDTERM 2', 'FINAL', 'LAB ', 'ATTENDANCE',
       'LETTER GRADE'],
      dtype='object')

In [54]:
df2.drop('LAB ', axis=1, inplace=True)

In [55]:
df2

           ID  MIDTERM 1  MIDTERM 2  FINAL  ATTENDANCE  LETTER GRADE
0   210206004       24.0        0.0    NaN        0.45           NaN
1   210206040       62.0       25.0   65.0        0.60           NaN
2   220206017        NaN        NaN    NaN        0.00           NaN
3   220206047       46.0       45.0   28.0        0.65           NaN
4   230206003       29.0       40.0   24.0        0.70           NaN
5   230206007      100.0      100.0   63.0        1.00           NaN
6   230206012       83.0       95.0   85.0        0.80           NaN
7   230206023        NaN        NaN    NaN        0.00           NaN
8   230206031        NaN        NaN    NaN        0.00           NaN
9   230206046       81.0       70.0   60.0        1.00           NaN
10  230206057       48.0       60.0   32.0        0.90           NaN
11  240206004       55.0        4.0   31.0        0.45           NaN
12  240206011       82.0       95.0   56.0        0.60           NaN
13  240206023      100.0      105.0   81.0        1.00           NaN
14  240206025       84.0       70.0   71.0        0.60           NaN
15  240206026       58.0       13.0   41.0        0.75           NaN
16  240206028       37.0        0.0    NaN        0.45           NaN
17  240206031       49.0       50.0   57.0        0.70           NaN
18  240206043       56.0       30.0   40.0        0.95           NaN
19  240206047       63.0       30.0   53.0        0.90           NaN
20  240206048       66.0       15.0   36.0        0.65           NaN
21  240206052       26.0       35.0   24.0        0.80           NaN
22  240206053       74.0       45.0   40.0        0.65           NaN
23  240206103       54.0        5.0   31.0        0.75           NaN
24  240206131       17.0       40.0   19.0        0.85           NaN
25  240206157       14.0        NaN    NaN        0.00           NaN
26  240206176        8.0       17.0   12.0        0.60           NaN
27  250206001       95.0       65.0   64.0        0.85           NaN
28  250206002       56.0       20.0   67.0        0.85           NaN
29  250206004      100.0       95.0   54.0        1.00           NaN
..        ...        ...        ...    ...         ...           ...
67  250206051        NaN        NaN    NaN        0.55           NaN
68  250206052       54.0      105.0   26.0        0.85           NaN
69  250206053       40.0       10.0   36.0        0.90           NaN
70  250206054       29.0       30.0   46.0        0.80           NaN
71  250206055        NaN        NaN    NaN        0.25           NaN
72  250206056       10.0        0.0    0.0        1.00           NaN
73  250206057       23.0       35.0   75.0        0.75           NaN
74  250206058       66.0       25.0   22.0        0.85           NaN
75  250206059       44.0       35.0   69.0        0.85           NaN
76  250206060       58.0       60.0   33.0        0.90           NaN
77  250206062       89.0       73.0   21.0        0.90           NaN
78  250206073       72.0       45.0   25.0        0.70           NaN
79  250206076        NaN        NaN    NaN        0.05           NaN
80  250206079        NaN        NaN    NaN        0.05           NaN
81  250206081       39.0       20.0    8.0        0.95           NaN
82  250206082       52.0        NaN    NaN        0.65           NaN
83  250206083       21.0        0.0   10.0        0.90           NaN
84  250206084        NaN        NaN    NaN        0.05           NaN
85  260206003       88.0       43.0   58.0        1.00           NaN
86  260206005        8.0       15.0   12.0        0.70           NaN
87  260206008       70.0       25.0   24.0        0.95           NaN
88  260206018       39.0        5.0    NaN        0.70           NaN
89  260206019       37.0        5.0   53.0        0.70           NaN
90  260206040       19.0       25.0   13.0        0.90           NaN
91  260206044       21.0        0.0    NaN        0.65           NaN
92  260206050       22.0       40.0   32.0        0.45           NaN
93  260206074       94.0       88.0   40.0        1.00           NaN
94  260206075       20.0        NaN    NaN        0.40           NaN
95  260206077       33.0       13.0    NaN        0.80           NaN
96  260206079        0.0        0.0    NaN        0.80           NaN

[97 rows x 6 columns]

In [56]:
df2.insert(4, column='LAB', value=df_lab1['Term Grade'])

In [57]:
df2

,ID,MIDTERM 1,MIDTERM 2,FINAL,LAB,ATTENDANCE,LETTER GRADE
0,210206004,24.0,0.0,NaN,45,0.45,NaN
1,210206040,62.0,25.0,65.0,"62,94444444",0.60,NaN
2,220206017,NaN,NaN,NaN,0,0.00,NaN
3,220206047,46.0,45.0,28.0,"54,02777778",0.65,NaN
4,230206003,29.0,40.0,24.0,"76,38888889",0.70,NaN
5,230206007,100.0,100.0,63.0,"88,47222222",1.00,NaN
6,230206012,83.0,95.0,85.0,"78,33333333",0.80,NaN
7,230206023,NaN,NaN,NaN,0,0.00,NaN
8,230206031,NaN,NaN,NaN,0,0.00,NaN
9,230206046,81.0,70.0,60.0,"75,69444444",1.00,NaN
10,230206057,48.0,60.0,32.0,"81,66666667",0.90,NaN
11,240206004,55.0,4.0,31.0,"70,02777778",0.45,NaN
12,240206011,82.0,95.0,56.0,"82,77777778",0.60,NaN
13,240206023,100.0,105.0,81.0,"84,72222222",1.00,NaN
14,240206025,84.0,70.0,71.0,"88,88888889",0.60,NaN
15,240206026,58.0,13.0,41.0,"75,02777778",0.75,NaN
16,240206028,37.0,0.0,NaN,"62,5",0.45,NaN
17,240206031,49.0,50.0,57.0,"84,44444444",0.70,NaN
18,240206043,56.0,30.0,40.0,"70,97222222",0.95,NaN
19,240206047,63.0,30.0,53.0,"78,75",0.90,NaN
20,240206048,66.0,15.0,36.0,"71,25",0.65,NaN
21,240206052,26.0,35.0,24.0,"82,22222222",0.80,NaN
22,240206053,74.0,45.0,40.0,"74,86111111",0.65,NaN
23,240206103,54.0,5.0,31.0,"49,58333333",0.75,NaN
24,240206131,17.0,40.0,19.0,"72,77777778",0.85,NaN
25,240206157,14.0,NaN,NaN,"2,638888889",0.00,NaN
26,240206176,8.0,17.0,12.0,"67,41666667",0.60,NaN
27,250206001,95.0,65.0,64.0,"85,83333333",0.85,NaN
28,250206002,56.0,20.0,67.0,"69,75",0.85,NaN
29,250206004,100.0,95.0,54.0,"89,44444444",1.00,NaN
...,...,...,...,...,...,...,...
67,250206051,NaN,NaN,NaN,"25,41666667",0.55,NaN
68,250206052,54.0,105.0,26.0,"74,16666667",0.85,NaN
69,250206053,40.0,10.0,36.0,"81,94444444",0.90,NaN
70,250206054,29.0,30.0,46.0,"58,08333333",0.80,NaN
71,250206055,NaN,NaN,NaN,0,0.25,NaN
72,250206056,10.0,0.0,0.0,"60,61111111",1.00,NaN
73,250206057,23.0,35.0,75.0,"87,22222222",0.75,NaN
74,250206058,66.0,25.0,22.0,81,0.85,NaN
75,250206059,44.0,35.0,69.0,"82,11111111",0.85,NaN
76,250206060,58.0,60.0,33.0,"70,36111111",0.90,NaN
77,250206062,89.0,73.0,21.0,"86,25",0.90,NaN
78,250206073,72.0,45.0,25.0,"83,33333333",0.70,NaN
79,250206076,NaN,NaN,NaN,0,0.05,NaN
80,250206079,NaN,NaN,NaN,0,0.05,NaN
81,250206081,39.0,20.0,8.0,70,0.95,NaN
82,250206082,52.0,NaN,NaN,"50,58333333",0.65,NaN
83,250206083,21.0,0.0,10.0,"80,97222222",0.90,NaN
84,250206084,NaN,NaN,NaN,0,0.05,NaN
85,260206003,88.0,43.0,58.0,"75,41666667",1.00,NaN
86,260206005,8.0,15.0,12.0,"61,55555556",0.70,NaN
87,260206008,70.0,25.0,24.0,"85,52777778",0.95,NaN
88,260206018,39.0,5.0,NaN,56,0.70,NaN
89,260206019,37.0,5.0,53.0,"81,52777778",0.70,NaN
90,260206040,19.0,25.0,13.0,"61,55555556",0.90,NaN
91,260206044,21.0,0.0,NaN,"42,63888889",0.65,NaN
92,260206050,22.0,40.0,32.0,"70,94444444",0.45,NaN
93,260206074,94.0,88.0,40.0,75,1.00,NaN
94,260206075,20.0,NaN,NaN,"47,63888889",0.40,NaN
95,260206077,33.0,13.0,NaN,"59,33333333",0.80,NaN
96,260206079,0.0,0.0,NaN,"70,86111111",0.80,NaN

In [58]:
df2.loc[0, 'LAB']

'45'

In [59]:
df2.loc[0]

ID              210206004
MIDTERM 1              24
MIDTERM 2               0
FINAL                 NaN
LAB                    45
ATTENDANCE           0.45
LETTER GRADE          NaN
Name: 0, dtype: object

In [60]:
type(df2.loc[0])

pandas.core.series.Series

In [61]:
df2.loc[0][0]

'210206004'

In [62]:
df2.loc[0]['ID']

'210206004'

In [63]:
import numpy as np
df2.loc[0]['LETTER GRADE'] == np.NaN

False

In [64]:
pd.isna(df2.loc[0]['LETTER GRADE'])

True

In [65]:
len(df2.loc[0])

7

In [66]:
np.NaN * 7

nan

In [67]:
np.NaN + 7

nan

In [68]:
x = 5

In [69]:
y = x + np.NaN

In [70]:
y

nan